Dist.cpp
double sinx[361][361]
Referenced by dist2UTM, ReadParams.
double cosx[361][361]
Referenced by dist2UTM, ReadParams.
double asin2sqx[1001][1001]
Referenced by dist2UTM, ReadParams.
double dist2UTM(double x1, double y1, double x2, double y2)
References asin2sqx, cosx, EARTHRADIUS, P, sinx, PARAM::SpatialBoundingBox.
Referenced by dist2, dist2_cc, dist2_cc_min, dist2_mm, dist2_raw.
double dist2(person *a, person *b)
References dist2UTM, PARAM::DoPeriodicBoundaries, PARAM::DoUTM_coords, PARAM::height, PERSON::hh, Households, HOUSEHOLD::loc_x, HOUSEHOLD::loc_y, P, PARAM::width.
Referenced by InfectSweep.
double dist2_cc(cell *a, cell *b)
References Cells, PARAM::cheight, PARAM::cwidth, dist2UTM, PARAM::DoPeriodicBoundaries, PARAM::DoUTM_coords, PARAM::height, PARAM::nch, P, PARAM::width.
Referenced by SetupModel.
double dist2_cc_min(cell *a, cell *b)
References Cells, PARAM::cheight, PARAM::cwidth, dist2UTM, PARAM::DoPeriodicBoundaries, PARAM::DoUTM_coords, PARAM::height, PARAM::nch, P, PI, PARAM::width.
Referenced by InitKernel.
double dist2_mm(microcell *a, microcell *b)
References dist2UTM, PARAM::DoPeriodicBoundaries, PARAM::DoUTM_coords, PARAM::height, Mcells, PARAM::mcheight, PARAM::mcwidth, PARAM::nmch, P, PARAM::width.
Referenced by TreatSweep.
double dist2_raw(double ax, double ay, double bx, double by)
References dist2UTM, PARAM::DoPeriodicBoundaries, PARAM::DoUTM_coords, PARAM::height, P, PARAM::width.
Referenced by AssignPeopleToPlaces, InfectSweep, ReadAirTravel, SaveDistribs, SetupAirports, SetupModel, TravelDepartSweep.