Kernels.h
SPATIALSIM_KERNELS_H_INCLUDED_
double* nKernel
Referenced by InitKernel, numKernel, SetupModel.
double * nKernelHR
Referenced by InitKernel, numKernel, SetupModel.
void InitKernel(int, double)
References CellLookup, Cells, dist2_cc_min, ExpKernel, GaussianKernel, Kernel, PARAM::KernelDelta, PARAM::KernelType, PARAM::NCP, NK_HR, nKernel, nKernelHR, NKR, numKernel, P, PowerExpKernel, PowerKernel, PowerKernelB, PowerKernelUS, StepKernel, CELL::tot_prob.
Referenced by AssignPeopleToPlaces, SetupAirports, SetupModel.
double ExpKernel(double)
References PARAM::KernelScale, P.
Referenced by InitKernel.
double PowerKernel(double)
References PARAM::KernelScale, PARAM::KernelShape, P.
Referenced by InitKernel.
double PowerKernelB(double)
References PARAM::KernelScale, PARAM::KernelShape, P.
Referenced by InitKernel.
double PowerKernelUS(double)
References PARAM::KernelP3, PARAM::KernelP4, PARAM::KernelScale, PARAM::KernelShape, P.
Referenced by InitKernel.
double PowerExpKernel(double)
References PARAM::KernelP3, PARAM::KernelP4, PARAM::KernelScale, PARAM::KernelShape, P.
Referenced by InitKernel.
double GaussianKernel(double)
References PARAM::KernelScale, P.
Referenced by InitKernel.
double StepKernel(double)
References PARAM::KernelScale, P.
Referenced by InitKernel.
double numKernel(double)
References ERR_CRITICAL, PARAM::KernelDelta, NK_HR, nKernel, nKernelHR, NKR, P.
Referenced by AssignPeopleToPlaces, InfectSweep, InitKernel, SetupAirports, TravelDepartSweep.