Rand.h
Xm1
Referenced by ranf, ranf_mt, setall.
Xm2
Referenced by ranf, ranf_mt, setall.
Xa1
Referenced by ranf, ranf_mt.
Xa2
Referenced by ranf, ranf_mt.
Xa1vw
Referenced by setall.
Xa2vw
Referenced by setall.
int** SamplingQueue
Referenced by InfectSweep, SampleWithoutReplacement, SetupPopulation.
long* Xcg1
Referenced by ranf, ranf_mt, setall, SetupModel.
long * Xcg2
Referenced by ranf, ranf_mt, setall, SetupModel.
long ignbin(long, double)
References ABS, ERR_CRITICAL, ignbin, minF, ranf.
Referenced by ignbin.
long ignpoi(double)
References fsign, ignpoi, maxF, minF, ranf, sexpo, snorm.
Referenced by AssignPeopleToPlaces, ignpoi, RunModel.
long ignbin_mt(long, double, int)
References ABS, ERR_CRITICAL, ignbin_mt, minF, ranf_mt.
Referenced by ignbin_mt, InfectSweep, SetupPopulation, StratifyPlaces.
long ignpoi_mt(double, int)
References fsign, ignpoi_mt, maxF, minF, ranf_mt, sexpo_mt, snorm_mt.
Referenced by AssignHouseholdAges, ignpoi_mt, InfectSweep, StratifyPlaces, TravelDepartSweep.
double ranf(void)
References CACHE_LINE_SIZE, Xa1, Xa2, Xcg1, Xcg2, Xm1, Xm2.
Referenced by AssignPeopleToPlaces, gen_gamma, gen_norm, ignbin, ignpoi, main, ReadInterventions, RunModel, SeedInfection, SetupModel, SetupPopulation, sexpo, sgamma, snorm.
double ranf_mt(int)
References CACHE_LINE_SIZE, Xa1, Xa2, Xcg1, Xcg2, Xm1, Xm2.
Referenced by AssignHouseholdAges, AssignPeopleToPlaces, ChooseFinalDiseaseSeverity, ChooseFromICDF, DoCase, DoDetectedCase, DoFalseCase, DoIncub, DoInfect, DoPlaceClose, gen_gamma_mt, gen_norm_mt, ignbin_mt, ignpoi_mt, IncubRecoverySweep, InfectSweep, InitModel, SampleWithoutReplacement, SetupModel, SetupPopulation, sexpo_mt, sgamma_mt, snorm_mt, StratifyPlaces, TravelDepartSweep, TreatSweep.
void setall(long, long)
References CACHE_LINE_SIZE, MAX_NUM_THREADS, mltmod, Xa1vw, Xa2vw, Xcg1, Xcg2, Xm1, Xm2.
Referenced by main, RunModel, SetupModel.
double sexpo_mt(int)
References ranf_mt, sexpo_mt.
Referenced by ignpoi_mt, sexpo_mt, sgamma_mt.
double sexpo(void)
References ranf, sexpo.
Referenced by ignpoi, sexpo, sgamma.
long mltmod(long, long, long)
References h, mltmod.
Referenced by mltmod, setall.
double snorm(void)
References h, ranf, snorm.
Referenced by gen_lognormal, ignpoi, sgamma, snorm.
double snorm_mt(int)
References h, ranf_mt, snorm_mt.
Referenced by gen_lognormal_mt, ignpoi_mt, sgamma_mt, snorm_mt.
double fsign(double, double)
Referenced by ignpoi, ignpoi_mt, sgamma, sgamma_mt.
double gen_norm(double, double)
References ranf.
Referenced by gen_gamma.
double gen_norm_mt(double, double, int)
References ranf_mt.
Referenced by gen_gamma_mt.
double gen_gamma(double, double)
References ERR_CRITICAL, gen_norm, ranf.
double gen_gamma_mt(double, double, int)
References ERR_CRITICAL, gen_norm_mt, ranf_mt.
Referenced by DoIncub, SetupModel.
double gen_lognormal(double, double)
References snorm.
Referenced by AssignPeopleToPlaces.
double gen_lognormal_mt(double, double, int)
References snorm_mt.
double sgamma(double)
References fsign, ranf, sexpo, sgamma, snorm.
Referenced by sgamma.
double sgamma_mt(double, int)
References fsign, ranf_mt, sexpo_mt, sgamma_mt, snorm_mt.
Referenced by sgamma_mt.
void SampleWithoutReplacement(int, int, int)
References MAX_PLACE_SIZE, PI, ranf_mt, SamplingQueue.
Referenced by InfectSweep.