Rand.cpp
ABS
Referenced by ignbin, ignbin_mt.
minF
Referenced by ignbin, ignbin_mt, ignpoi, ignpoi_mt.
maxF
Referenced by ignpoi, ignpoi_mt.
h
Referenced by mltmod, snorm, snorm_mt.
long* Xcg1
Referenced by ranf, ranf_mt, setall, SetupModel.
long * Xcg2
Referenced by ranf, ranf_mt, setall, SetupModel.
int** SamplingQueue
Referenced by InfectSweep, SampleWithoutReplacement, SetupPopulation.
double ranf(void)
References CACHE_LINE_SIZE, Xa1, Xa2, Xcg1, Xcg2, Xm1, Xm2.
Referenced by AssignPeopleToPlaces, gen_gamma, gen_norm, ignbin, ignpoi, main, ReadInterventions, RunModel, SeedInfection, SetupModel, SetupPopulation, sexpo, sgamma, snorm.
double ranf_mt(int tn)
References CACHE_LINE_SIZE, Xa1, Xa2, Xcg1, Xcg2, Xm1, Xm2.
Referenced by AssignHouseholdAges, AssignPeopleToPlaces, ChooseFinalDiseaseSeverity, ChooseFromICDF, DoCase, DoDetectedCase, DoFalseCase, DoIncub, DoInfect, DoPlaceClose, gen_gamma_mt, gen_norm_mt, ignbin_mt, ignpoi_mt, IncubRecoverySweep, InfectSweep, InitModel, SampleWithoutReplacement, SetupModel, SetupPopulation, sexpo_mt, sgamma_mt, snorm_mt, StratifyPlaces, TravelDepartSweep, TreatSweep.
void setall(long iseed1, long iseed2)
References CACHE_LINE_SIZE, MAX_NUM_THREADS, mltmod, Xa1vw, Xa2vw, Xcg1, Xcg2, Xm1, Xm2.
Referenced by main, RunModel, SetupModel.
long mltmod(long a, long s, long m)
References h, mltmod.
Referenced by mltmod, setall.
long ignbin(long n, double pp)
References ABS, ERR_CRITICAL, ignbin, minF, ranf.
Referenced by ignbin.
long ignpoi(double mu)
References fsign, ignpoi, maxF, minF, ranf, sexpo, snorm.
Referenced by AssignPeopleToPlaces, ignpoi, RunModel.
long ignpoi_mt(double mu, int tn)
References fsign, ignpoi_mt, maxF, minF, ranf_mt, sexpo_mt, snorm_mt.
Referenced by AssignHouseholdAges, ignpoi_mt, InfectSweep, StratifyPlaces, TravelDepartSweep.
long ignbin_mt(long n, double pp, int tn)
References ABS, ERR_CRITICAL, ignbin_mt, minF, ranf_mt.
Referenced by ignbin_mt, InfectSweep, SetupPopulation, StratifyPlaces.
double sexpo(void)
References ranf, sexpo.
Referenced by ignpoi, sexpo, sgamma.
double sexpo_mt(int tn)
References ranf_mt, sexpo_mt.
Referenced by ignpoi_mt, sexpo_mt, sgamma_mt.
double snorm(void)
References h, ranf, snorm.
Referenced by gen_lognormal, ignpoi, sgamma, snorm.
double snorm_mt(int tn)
References h, ranf_mt, snorm_mt.
Referenced by gen_lognormal_mt, ignpoi_mt, sgamma_mt, snorm_mt.
double fsign(double num, double sign)
Referenced by ignpoi, ignpoi_mt, sgamma, sgamma_mt.
double sgamma(double a)
References fsign, ranf, sexpo, sgamma, snorm.
Referenced by sgamma.
double sgamma_mt(double a, int tn)
References fsign, ranf_mt, sexpo_mt, sgamma_mt, snorm_mt.
Referenced by sgamma_mt.
double gen_norm(double mu, double sd)
References ranf.
Referenced by gen_gamma.
double gen_norm_mt(double mu, double sd, int tn)
References ranf_mt.
Referenced by gen_gamma_mt.
double gen_gamma(double beta, double alpha)
References ERR_CRITICAL, gen_norm, ranf.
double gen_gamma_mt(double beta, double alpha, int tn)
References ERR_CRITICAL, gen_norm_mt, ranf_mt.
Referenced by DoIncub, SetupModel.
double gen_lognormal(double mu, double sigma)
References snorm.
Referenced by AssignPeopleToPlaces.
double gen_lognormal_mt(double mu, double sigma, int tn)
References snorm_mt.
void SampleWithoutReplacement(int tn, int k, int n)
References MAX_PLACE_SIZE, PI, ranf_mt, SamplingQueue.
Referenced by InfectSweep.