SetupModel.h
SPATIALSIM_SETUPMODEL_H_INCLUDED_
NETWORK_FILE_VERSION
Referenced by LoadPeopleToPlaces, SavePeopleToPlaces.
typedef struct BIN_FILE bin_file
char OutFile[1024][1024]
Referenced by main, ReadAirTravel, SaveDistribs, SaveEvents, SaveOriginDestMatrix, SaveRandomSeeds, SaveResults, SaveSummaryResults.
char OutDensFile[1024][1024]
Referenced by main, SetupPopulation.
char RoadNetworkFile[1024][1024]
void SetupModel(char *, char *, char *, char *)
References BIN_FILE::ad, PARAM::AdunitLevel1Divisor, PARAM::AdunitLevel1Lookup, PARAM::AdunitLevel1Mask, AdUnits, PARAM::AgeInfectiousness, PARAM::AgeSusceptibility, AssignPeopleToPlaces, PARAM::bheight, PARAM::bheight2, BinFileBuf, PARAM::BinFileLen, PARAM::BitmapAspectScale, PARAM::BitmapScale, PARAM::bminx, PARAM::bminy, PARAM::BoundingBox, PARAM::bwidth, CACHE_LINE_SIZE, case_household_av, CDF_RES, PARAM::CellPop2, Cells, PARAM::cheight, PARAM::ClusterDigitalContactUsers, BIN_FILE::cnt, ADMINUNIT::cnt_id, PARAM::CountryDivisor, RESULTS::Critical, RESULTS::CritRecov, RESULTS::CT, RESULTS::cumCritical, RESULTS::cumCritRecov, RESULTS::cumDC, RESULTS::cumILI, RESULTS::cumMild, RESULTS::cumSARI, RESULTS::cumT, RESULTS::cumTP, RESULTS::cumUT, RESULTS::cumV, PARAM::cwidth, RESULTS::D, RESULTS::DCT, PERSON::digitalContactTracingUser, dist2_cc, dist2_raw, PARAM::DoAdunitBoundaries, PARAM::DoAdUnits, PARAM::DoAirports, PARAM::DoBin, PARAM::DoDigitalContactTracing, PARAM::DoHeteroDensity, PARAM::DoHouseholds, DoInitUpdateProbs, PARAM::DoMassVacc, PARAM::DoPeriodicBoundaries, PARAM::DoPlaces, PARAM::DoRecordInfEvents, PARAM::DoSeverity, PARAM::DoSI, PARAM::DoSpatial, PARAM::DoSpecifyPop, ERR_CRITICAL, PARAM::ESocProportionCompliant, HOUSEHOLD::FirstPerson, fread_big, gen_gamma_mt, RESULTS::H, PARAM::height, PERSON::hh, HOST_AGE_GROUP, HOST_AGE_YEAR, Hosts, HOTEL_PLACE_TYPE, PARAM::HouseholdDenomLookup, Households, PARAM::HouseholdSizeDistrib, PARAM::HouseholdTrans, RESULTS::I, CELL::I, ADMINUNIT::id, RESULTS::ILI, RESULTS::incAA, RESULTS::incACS, RESULTS::incAH, RESULTS::incAPA, RESULTS::incAPC, RESULTS::incAPCS, RESULTS::incC, RESULTS::incCC, RESULTS::incCritical, RESULTS::incCritRecov, RESULTS::incCT, RESULTS::incD, RESULTS::incDC, RESULTS::incDCT, RESULTS::incH, RESULTS::incI, RESULTS::incILI, RESULTS::incL, RESULTS::incMild, RESULTS::incR, RESULTS::incSARI, RESULTS::incTC, indivR0_av, inf_household_av, infcountry_av, infcountry_num, INFECT_TYPE_MASK, PARAM::infectious_icdf, PERSON::infectiousness, PARAM::infectiousness, PARAM::InfectiousnessGamA, PARAM::InfectiousnessGamR, PARAM::InfectiousnessSD, PARAM::InfectiousPeriod, InfEventLog, InfStat_Susceptible, inftype_av, InitBMHead, InitKernel, PARAM::KernelDelta, PARAM::KernelP3, PARAM::KernelP4, PARAM::KernelScale, PARAM::KernelShape, PARAM::KernelType, PERSON::keyworker, PARAM::KeyWorkerHouseProp, PARAM::KeyWorkerIncHouseNum, PARAM::KeyWorkerNum, PARAM::KeyWorkerPlaceNum, PARAM::KeyWorkerPopNum, PARAM::KeyWorkerPropInKeyPlaces, RESULTS::L, CELL::L, PARAM::LatentToSymptDelay, LoadPeopleToPlaces, PARAM::LoadSaveNetwork, PARAM::LocalBeta, PARAM::LocationInitialInfection, MAX_CONTACTS, MAX_COUNTRIES, MAX_GEN_REC, MAX_HOUSEHOLD_SIZE, MAX_NUM_THREADS, MAX_SEC_REC, PARAM::MaxInfEvents, Mcells, PARAM::mcheight, PARAM::mcwidth, PLACE::members, RESULTS::Mild, PARAM::MoveKernelP3, PARAM::MoveKernelP4, PARAM::MoveKernelScale, PARAM::MoveKernelShape, PARAM::MoveKernelType, POPVAR::mvacc_queue, PARAM::N, CELL::n, POPVAR::n_mvacc, PARAM::NC, PARAM::nch, PARAM::ncw, PARAM::NDigitalContactUsers, PARAM::NDigitalHouseholdUsers, nEvents, PARAM::NH, HOUSEHOLD::nh, HOUSEHOLD::nhr, nKernel, nKernelHR, NKR, PARAM::NMC, PARAM::nmch, PARAM::NMCL, PARAM::nmcw, PARAM::Nplace, PARAM::NRactE, PARAM::NRactNE, NUM_AGE_GROUPS, NUM_PLACE_TYPES, NUM_PLACE_TYPES_NOAIR, PARAM::NumAdunits, PARAM::NumSamples, PARAM::NumSeedLocations, PARAM::NumThreads, PARAM::OutputBitmap, P, PeakHeightSS, PeakHeightSum, PeakTimeSS, PeakTimeSum, PARAM::PlaceCloseAdunitPlaceTypes, PERSON::PlaceLinks, Places, PARAM::PlaceTypeGroupSizeParam1, PARAM::PlaceTypeNum, PARAM::PlaceTypePropBetweenGroupLinks, PARAM::PlaceTypeTrans, BIN_FILE::pop, PARAM::PropAgeGroup, PARAM::ProportionSmartphoneUsersByAge, PARAM::ProportionSymptomatic, PARAM::PropPopUsingDigitalContactTracing, RESULTS::R, CELL::R, PARAM::R0, PARAM::R0household, PARAM::R0places, PARAM::R0scale, PARAM::R0spatial, ranf, ranf_mt, RESULTS::Rdenom, PERSON::recovery_time, PARAM::RelativeSpatialContact, RESULTS::S, CELL::S, RESULTS::SARI, SaveAgeDistrib, SavePeopleToPlaces, PARAM::scalex, PARAM::scaley, PARAM::seed1, PARAM::seed2, setall, SetupAirports, SetupPopulation, PARAM::SpatialBoundingBox, State, StratifyPlaces, PARAM::SymptInfectiousness, PARAM::SymptPlaceTypeContactRate, PARAM::SymptPlaceTypeWithdrawalProp, PARAM::SymptSpatialContactRate, TimeSeries, PARAM::TimeStep, TSMean, TSMeanE, TSMeanNE, TSVar, TSVarE, TSVarNE, UpdateProbs, PARAM::VaccPriorityGroupAge, PARAM::VaccProp, PARAM::width, BIN_FILE::x, Xcg1, Xcg2, BIN_FILE::y.
Referenced by main.
void SetupPopulation(char *, char *, char *)
References BIN_FILE::ad, MICROCELL::adunit, PARAM::AdunitLevel1Divisor, PARAM::AdunitLevel1Lookup, PARAM::AdunitLevel1Mask, AdUnits, PERSON::age, AGE_GROUP_WIDTH, AgeDist, AgeDist2, AssignHouseholdAges, PLACE::AvailByAge, BinFileBuf, PARAM::BinFileLen, CACHE_LINE_SIZE, CellLookup, POPVAR::CellMemberArray, Cells, POPVAR::CellSuscMemberArray, PARAM::cheight, BIN_FILE::cnt, ADMINUNIT::cnt_id, MICROCELL::country, PLACE::country, CELL::cumTC, PARAM::cwidth, denom_household, PARAM::DoAdunitBoundaries, PARAM::DoAdunitDemog, PARAM::DoAdUnits, PARAM::DoBin, PARAM::DoCorrectAdunitPop, PARAM::DoCorrectAgeDist, PARAM::DoDigitalContactTracing, PARAM::DoHeteroDensity, PARAM::DoHouseholds, PARAM::DoOriginDestinationMatrix, PARAM::DoPlaces, PARAM::DoRandomInitialInfectionLoc, PARAM::DoSchoolFile, ERR_CRITICAL, HOUSEHOLD::FirstPerson, fread_big, fwrite_big, PERSON::hh, HOST_AGE_GROUP, HOST_AGE_YEAR, Hosts, HOTEL_PLACE_TYPE, Households, PARAM::HouseholdSizeDistrib, CELL::I, ADMINUNIT::id, ignbin_mt, PERSON::inf, INF_QUEUE_SCALE, PARAM::InfQueuePeakLength, InfStat_Susceptible, POPVAR::InvAgeDist, CELL::L, PERSON::listpos, HOUSEHOLD::loc_x, PLACE::loc_x, HOUSEHOLD::loc_y, PLACE::loc_y, PARAM::LocationInitialInfection, MAX_ADUNITS, MAX_HOUSEHOLD_SIZE, MAX_PLACE_SIZE, PERSON::mcell, PLACE::mcell, mcell_adunits, mcell_country, mcell_dens, mcell_num, McellLookup, Mcells, PARAM::mcheight, PARAM::mcwidth, MICROCELL::members, CELL::members, PARAM::N, MICROCELL::n, CELL::n, PLACE::n, ADMINUNIT::n, PARAM::NC, PARAM::nch, PARAM::NCP, PARAM::NH, HOUSEHOLD::nh, HOUSEHOLD::nhr, PARAM::NMC, PARAM::nmch, PARAM::NMCL, PARAM::NMCP, MICROCELL::np, PARAM::Nplace, PARAM::nsp, NUM_AGE_GROUPS, PARAM::NumAdunits, PARAM::NumInitialInfections, PARAM::NumThreads, ADMINUNIT::origin_dest, OutDensFile, PARAM::OutputDensFile, P, PERSON::pcell, PI, MICROCELL::places, Places, PARAM::PlaceTypeAgeMax, PARAM::PlaceTypeAgeMax2, PARAM::PlaceTypeAgeMax3, PARAM::PlaceTypeAgeMin, PARAM::PlaceTypeAgeMin2, PARAM::PlaceTypeAgeMin3, PARAM::PlaceTypeMaxAgeRead, PARAM::PlaceTypeMeanSize, PARAM::PlaceTypeNum, PARAM::PlaceTypePropAgeGroup, PARAM::PlaceTypePropAgeGroup2, PARAM::PlaceTypePropAgeGroup3, BIN_FILE::pop, PARAM::PopByAdunit, PARAM::PropAgeGroup, PropPlaces, PropPlacesC, ranf, ranf_mt, RevCellLookup, CELL::S, SamplingQueue, PARAM::SpatialBoundingBox, State, StateT, CELL::susceptible, BIN_FILE::x, BIN_FILE::y.
Referenced by SetupModel.
void SetupAirports(void)
References PARAM::AirportKernelP3, PARAM::AirportKernelP4, PARAM::AirportKernelScale, PARAM::AirportKernelShape, PARAM::AirportKernelType, MICROCELL::AirportList, Airports, AIRPORT::DestMcells, AIRPORT::DestPlaces, dist2_raw, ERR_CRITICAL, HOTEL_PLACE_TYPE, HOTELS_PER_1000PASSENGER, INDEXLIST::id, InitKernel, AIRPORT::Inv_DestMcells, AIRPORT::Inv_DestPlaces, PARAM::KernelP3, PARAM::KernelP4, PARAM::KernelScale, PARAM::KernelShape, PARAM::KernelType, MAX_DIST_AIRPORT_TO_HOTEL, Mcells, PARAM::mcheight, PARAM::mcwidth, MIN_HOTELS_PER_AIRPORT, PARAM::MoveKernelP3, PARAM::MoveKernelP4, PARAM::MoveKernelScale, PARAM::MoveKernelShape, PARAM::MoveKernelType, PARAM::Nairports, PARAM::NMC, PARAM::nmch, PARAM::NMCP, NNA, PARAM::Nplace, AIRPORT::num_mcell, AIRPORT::num_place, numKernel, P, Places, INDEXLIST::prob, AIRPORT::total_traffic.
Referenced by SetupModel.
void SetupRoads(void)
void AssignHouseholdAges(int, int, int)
References AGE_GROUP_WIDTH, PARAM::DoAdunitDemog, PARAM::DoAdUnits, PARAM::DoHouseholds, Hosts, ignpoi_mt, POPVAR::InvAgeDist, MAX_CHILD_AGE, MAX_FM_PARTNER_AGE_GAP, MAX_HOUSEHOLD_SIZE, MAX_MF_PARTNER_AGE_GAP, MAX_PARENT_AGE_GAP, Mcells, MEAN_CHILD_AGE_GAP, MIN_ADULT_AGE, MIN_PARENT_AGE_GAP, NOCHILD_PERS_AGE, NUM_AGE_GROUPS, OLD_PERS_AGE, OLDER_GEN_GAP, ONE_CHILD_FOUR_PERS_PROB, ONE_CHILD_PROB_YOUNGEST_CHILD_UNDER_FIVE, ONE_CHILD_TWO_PERS_PROB, ONE_PERS_HOUSE_PROB_OLD, ONE_PERS_HOUSE_PROB_YOUNG, P, PROB_YOUNGEST_CHILD_UNDER_FIVE, PROP_OTHER_PARENT_AWAY, ranf_mt, State, THREE_CHILD_FIVE_PERS_PROB, TWO_CHILD_THREE_PERS_PROB, TWO_CHILDREN_PROB_YOUNGEST_UNDER_FIVE, TWO_PERS_HOUSE_PROB_OLD, TWO_PERS_HOUSE_PROB_YOUNG, YOUNG_AND_SINGLE, YOUNG_AND_SINGLE_SLOPE, ZERO_CHILD_THREE_PERS_PROB.
Referenced by SetupPopulation.
void AssignPeopleToPlaces(void)
References PLACE::AvailByAge, CACHE_LINE_SIZE, CellLookup, Cells, PARAM::cheight, CELL::cumTC, PARAM::cwidth, dist2_raw, PARAM::DoAdUnits, PARAM::DoPlaces, ERR_CRITICAL, gen_lognormal, HOST_AGE_YEAR, Hosts, HOTEL_PLACE_TYPE, Households, CELL::I, ignpoi, CELL::infected, PARAM::InhibitInterAdunitPlaceAssignment, InitKernel, CELL::InvCDF, PARAM::KernelP3, PARAM::KernelP4, PARAM::KernelScale, PARAM::KernelShape, PARAM::KernelType, CELL::L, PLACE::loc_y, MAX_NUM_THREADS, CELL::max_trans, PERSON::mcell, Mcells, CELL::members, PARAM::MoveKernelP3, PARAM::MoveKernelP4, PARAM::MoveKernelScale, PARAM::MoveKernelShape, PARAM::MoveKernelType, PARAM::N, CELL::n, PLACE::n, PARAM::NC, PARAM::nch, PARAM::NCP, PARAM::ncw, PARAM::nmch, PARAM::nmcw, MICROCELL::np, PARAM::Nplace, PARAM::nsp, NUM_PLACE_TYPES, numKernel, PARAM::NumThreads, P, PERSON::pcell, PERSON::PlaceLinks, MICROCELL::places, Places, PARAM::PlaceTypeKernelP3, PARAM::PlaceTypeKernelP4, PARAM::PlaceTypeKernelScale, PARAM::PlaceTypeKernelShape, PARAM::PlaceTypeKernelType, PARAM::PlaceTypeMaxAgeRead, PARAM::PlaceTypeMeanSize, PARAM::PlaceTypeNearestNeighb, PARAM::PlaceTypeNum, PARAM::PlaceTypeSizeMax, PARAM::PlaceTypeSizeOffset, PARAM::PlaceTypeSizePower, PARAM::PlaceTypeSizeSD, PropPlaces, CELL::R, ranf, ranf_mt, CELL::S, CELL::S0, CELL::susceptible, PLACE::treat_end_time, UpdateProbs.
Referenced by SetupModel.
void StratifyPlaces(void)
References PARAM::DoPlaceGroupTreat, PARAM::DoPlaces, ERR_CRITICAL, PLACE::group_size, PLACE::group_start, Hosts, HOTEL_PLACE_TYPE, ignbin_mt, ignpoi_mt, PLACE::members, PARAM::N, PLACE::n, PLACE::ng, PARAM::Nplace, NUM_PLACE_TYPES, PARAM::NumThreads, P, PERSON::PlaceGroupLinks, PERSON::PlaceLinks, Places, PARAM::PlaceTypeGroupSizeParam1, PARAM::PlaceTypeMeanSize, PARAM::PlaceTypeNum, ranf_mt, StateT.
Referenced by SetupModel.
void LoadPeopleToPlaces(char *)
References ERR_CRITICAL, fread_big, Hosts, PARAM::KernelP3, PARAM::KernelP4, PARAM::KernelScale, PARAM::KernelShape, PARAM::MoveKernelP3, PARAM::MoveKernelP4, PARAM::MoveKernelScale, PARAM::MoveKernelShape, PARAM::N, netbuf, NETWORK_FILE_VERSION, PARAM::Nplace, NUM_PLACE_TYPES_NOAIR, P, PERSON::PlaceLinks, PARAM::PlaceTypeNum, PARAM::seed1, PARAM::seed2.
Referenced by SetupModel.
void SavePeopleToPlaces(char *)
References ERR_CRITICAL, fwrite_big, Hosts, PARAM::N, NETWORK_FILE_VERSION, PARAM::Nplace, NUM_PLACE_TYPES_NOAIR, P, PARAM::PlaceTypeNum, PARAM::seed1, PARAM::seed2.
Referenced by SetupModel.
void SaveAgeDistrib(void)
References AgeDist, AgeDist2, PARAM::DoDeath, ERR_CRITICAL, POPVAR::InvAgeDist, PARAM::InvLifeExpecDist, NUM_AGE_GROUPS, OutFile, P, State.
Referenced by SetupModel.