SpatialSim.cpp
MAXINTFILE
Referenced by main.
param P
Referenced by AssignHouseholdAges, AssignPeopleToPlaces, CalcHouseInf, CalcHouseSusc, CalcPersonInf, CalcPersonSusc, CalcPlaceInf, CalcPlaceSusc, CalcSpatialInf, CalcSpatialSusc, CaptureBitmap, ChooseFinalDiseaseSeverity, ChooseFromICDF, DigitalContactTracingSweep, dist2, dist2_cc, dist2_cc_min, dist2_mm, dist2_raw, dist2UTM, DoCase, DoCritical, DoDeath, DoDeath_FromCriticalorSARI, DoDetectedCase, DoFalseCase, DoILI, DoImmune, DoIncub, DoInfect, DoMild, DoPlaceClose, DoPlaceOpen, DoProph, DoProphNoDelay, DoRecover, DoRecover_FromSeverity, DoRecoveringFromCritical, DoSARI, DoTreatCase, DoVacc, DoVaccNoDelay, ExpKernel, GaussianKernel, IncubRecoverySweep, InfectSweep, InitBMHead, InitKernel, LoadPeopleToPlaces, numKernel, PowerExpKernel, PowerKernel, PowerKernelB, PowerKernelUS, RecordEvent, SaveAgeDistrib, SavePeopleToPlaces, SetupAirports, SetupModel, SetupPopulation, StepKernel, StratifyPlaces, TravelDepartSweep, TravelReturnSweep, TreatSweep.
person* Hosts
Referenced by AssignHouseholdAges, AssignPeopleToPlaces, CalcHouseInf, CalcHouseSusc, CalcPersonInf, CalcPersonSusc, CalcPlaceInf, CalcPlaceSusc, CalcSpatialInf, CalcSpatialSusc, CaptureBitmap, DigitalContactTracingSweep, DoCase, DoCritical, DoDeath, DoDeath_FromCriticalorSARI, DoDetectedCase, DoFalseCase, DoILI, DoImmune, DoIncub, DoInfect, DoMild, DoPlaceClose, DoPlaceOpen, DoProph, DoProphNoDelay, DoRecover, DoRecover_FromSeverity, DoRecoveringFromCritical, DoSARI, DoTreatCase, DoVacc, DoVaccNoDelay, IncubRecoverySweep, InfectSweep, LoadPeopleToPlaces, RecordEvent, SavePeopleToPlaces, SetupModel, SetupPopulation, StratifyPlaces, TravelDepartSweep, TravelReturnSweep, TreatSweep.
household* Households
Referenced by AssignPeopleToPlaces, CalcHouseInf, CaptureBitmap, dist2, DoCase, DoDeath, DoDetectedCase, DoImmune, DoInfect, DoPlaceClose, DoPlaceOpen, DoProph, DoProphNoDelay, DoRecover, DoTreatCase, DoVacc, DoVaccNoDelay, InfectSweep, RecordEvent, SetupModel, SetupPopulation, TravelDepartSweep.
popvar State
Referenced by AssignHouseholdAges, DoDetectedCase, DoFalseCase, DoProph, DoProphNoDelay, DoTreatCase, DoVacc, DoVaccNoDelay, SaveAgeDistrib, SetupModel, SetupPopulation, TreatSweep.
popvar StateT[MAX_NUM_THREADS][MAX_NUM_THREADS]
Referenced by DigitalContactTracingSweep, DoCase, DoCritical, DoDeath, DoDeath_FromCriticalorSARI, DoDetectedCase, DoFalseCase, DoILI, DoInfect, DoMild, DoPlaceClose, DoPlaceOpen, DoProph, DoProphNoDelay, DoRecover_FromSeverity, DoRecoveringFromCritical, DoSARI, DoTreatCase, InfectSweep, SetupPopulation, StratifyPlaces, TreatSweep.
cell* Cells
Referenced by AssignPeopleToPlaces, CalcOriginDestMatrix_adunit, dist2_cc, dist2_cc_min, DoCase, DoDeath, DoImmune, DoIncub, DoInfect, DoProph, DoProphNoDelay, DoRecover, DoTreatCase, DoVacc, DoVaccNoDelay, InfectSweep, InitKernel, SetupModel, SetupPopulation, TravelDepartSweep.
cell ** CellLookup
Referenced by AssignPeopleToPlaces, IncubRecoverySweep, InfectSweep, InitKernel, SetupPopulation, TravelDepartSweep.
microcell* Mcells
Referenced by AssignHouseholdAges, AssignPeopleToPlaces, CalcHouseSusc, CalcPlaceSusc, CalcSpatialSusc, CaptureBitmap, dist2_mm, DoCase, DoCritical, DoDeath, DoDeath_FromCriticalorSARI, DoDetectedCase, DoILI, DoInfect, DoMild, DoPlaceClose, DoProph, DoProphNoDelay, DoRecover_FromSeverity, DoRecoveringFromCritical, DoSARI, DoTreatCase, InfectSweep, RecordEvent, SetupAirports, SetupModel, SetupPopulation, TravelDepartSweep, TreatSweep.
microcell ** McellLookup
Referenced by SetupPopulation, TreatSweep.
place** Places
Referenced by AssignPeopleToPlaces, DoDetectedCase, DoPlaceClose, DoPlaceOpen, IncubRecoverySweep, InfectSweep, SetupAirports, SetupModel, SetupPopulation, StratifyPlaces, TravelDepartSweep, TravelReturnSweep, TreatSweep.
adminunit AdUnits[MAX_ADUNITS][MAX_ADUNITS]
Referenced by CaptureBitmap, DigitalContactTracingSweep, DoDetectedCase, DoPlaceClose, InfectSweep, SetupModel, SetupPopulation, TreatSweep.
results* TimeSeries
Referenced by SetupModel.
results * TSMean
Referenced by SetupModel.
results * TSVar
Referenced by SetupModel.
results * TSMeanNE
Referenced by main, RecordInfTypes, RecordSample, SetupModel.
results * TSVarNE
Referenced by main, RecordInfTypes, RecordSample, SetupModel.
results * TSMeanE
Referenced by main, RecordInfTypes, SetupModel.
results * TSVarE
Referenced by main, RecordInfTypes, SetupModel.
airport* Airports
Referenced by SetupAirports, TravelDepartSweep.
bitmap_header* bmh
Referenced by CaptureBitmap, DoDeath, DoImmune, DoInfect, DoProph, DoProphNoDelay, DoRecover, DoTreatCase, DoVacc, DoVaccNoDelay, InitBMHead, OutputBitmap.
events* InfEventLog
Referenced by RecordEvent, SetupModel.
int* nEvents
Referenced by DoInfect, InitModel, RecordEvent, SaveEvents, SetupModel.
int* RevCellLookup
Referenced by SetupPopulation.
int count_ranf
Referenced by main.
int count_ranfmt
Referenced by main.
double** PopDensity
double * mcell_dens
Referenced by SetupPopulation.
int* mcell_adunits
Referenced by SetupPopulation.
int * mcell_num
Referenced by SetupPopulation.
int * mcell_country
Referenced by SetupPopulation.
double inftype[INFECT_TYPE_MASK][INFECT_TYPE_MASK]
Referenced by RecordInfTypes.
double inftype_av[INFECT_TYPE_MASK][INFECT_TYPE_MASK]
Referenced by RecordInfTypes, SetupModel.
double infcountry[MAX_COUNTRIES][MAX_COUNTRIES]
Referenced by RecordInfTypes.
double infcountry_av[MAX_COUNTRIES][MAX_COUNTRIES]
Referenced by RecordInfTypes, SaveSummaryResults, SetupModel.
double infcountry_num[MAX_COUNTRIES][MAX_COUNTRIES]
Referenced by RecordInfTypes, SaveSummaryResults, SetupModel.
double indivR0[MAX_SEC_REC][MAX_GEN_REC][MAX_SEC_REC][MAX_GEN_REC]
Referenced by RecordInfTypes.
double indivR0_av[MAX_SEC_REC][MAX_GEN_REC][MAX_SEC_REC][MAX_GEN_REC]
Referenced by RecordInfTypes, SaveSummaryResults, SetupModel.
double inf_household[MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1]
Referenced by RecordInfTypes.
double denom_household[MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1]
Referenced by SaveSummaryResults, SetupPopulation.
double inf_household_av[MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1]
Referenced by RecordInfTypes, SaveSummaryResults, SetupModel.
double AgeDist[NUM_AGE_GROUPS][NUM_AGE_GROUPS]
Referenced by SaveAgeDistrib, SaveSummaryResults, SetupPopulation.
double AgeDist2[NUM_AGE_GROUPS][NUM_AGE_GROUPS]
Referenced by SaveAgeDistrib, SetupPopulation.
double case_household[MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1]
Referenced by RecordInfTypes.
double case_household_av[MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1][MAX_HOUSEHOLD_SIZE+1]
Referenced by RecordInfTypes, SaveSummaryResults, SetupModel.
double PropPlaces[NUM_AGE_GROUPS *AGE_GROUP_WIDTH][NUM_PLACE_TYPES][NUM_AGE_GROUPS *AGE_GROUP_WIDTH][NUM_PLACE_TYPES]
Referenced by AssignPeopleToPlaces, SetupPopulation.
double PropPlacesC[NUM_AGE_GROUPS *AGE_GROUP_WIDTH][NUM_PLACE_TYPES][NUM_AGE_GROUPS *AGE_GROUP_WIDTH][NUM_PLACE_TYPES]
Referenced by SetupPopulation.
double AirTravelDist[MAX_DIST][MAX_DIST]
Referenced by ReadAirTravel.
double PeakHeightSum
Referenced by RecordInfTypes, SaveSummaryResults, SetupModel.
double PeakHeightSS
Referenced by RecordInfTypes, SaveSummaryResults, SetupModel.
double PeakTimeSum
Referenced by RecordInfTypes, SaveSummaryResults, SetupModel.
double PeakTimeSS
Referenced by RecordInfTypes, SaveSummaryResults, SetupModel.
float* bmi
Referenced by CaptureBitmap, InitBMHead.
float * bmi2
Referenced by CaptureBitmap, DoDeath, DoInfect, DoRecover, InitBMHead, InitModel.
float * bmi3
Referenced by CaptureBitmap, DoDeath, DoImmune, DoRecover, InitBMHead, InitModel.
float * bmi4
Referenced by CaptureBitmap, DoProph, DoProphNoDelay, DoTreatCase, DoVacc, DoVaccNoDelay, InitBMHead, InitModel.
char OutFile[1024][1024]
Referenced by main, OutputBitmap, ReadAirTravel, SaveAgeDistrib, SaveDistribs, SaveEvents, SaveOriginDestMatrix, SaveRandomSeeds, SaveResults, SaveSummaryResults.
char OutFileBase[1024][1024]
Referenced by InitBMHead, main.
char OutDensFile[1024][1024]
Referenced by main, SetupPopulation.
char SnapshotLoadFile[1024][1024]
Referenced by LoadSnapshot, main.
char SnapshotSaveFile[1024][1024]
Referenced by main, SaveSnapshot.
char AdunitFile[1024][1024]
Referenced by main, ReadParams.
int ns
Referenced by InitModel, RunModel.
int DoInitUpdateProbs
Referenced by InitModel, RunModel, SetupModel.
int InterruptRun
Referenced by main, RecordSample, RunModel.
unsigned int cntr
int PlaceDistDistrib[NUM_PLACE_TYPES][MAX_DIST][NUM_PLACE_TYPES][MAX_DIST]
Referenced by SaveDistribs.
int PlaceSizeDistrib[NUM_PLACE_TYPES][MAX_PLACE_SIZE][NUM_PLACE_TYPES][MAX_PLACE_SIZE]
Referenced by SaveDistribs.
FILE* KMLFile
FILE * KMLFile2
void ReadParams(char *, char *)
References ADMINUNIT::ad_name, ADUNIT_LOOKUP_SIZE, PARAM::AdunitBitmapDivisor, AdunitFile, PARAM::AdunitLevel1Divisor, PARAM::AdunitLevel1Lookup, PARAM::AdunitLevel1Mask, PARAM::AgeInfectiousness, PARAM::AgeSusceptibility, PARAM::AirportCloseDuration, PARAM::AirportCloseEffectiveness, PARAM::AirportCloseTimeStartBase, PARAM::AirportKernelP3, PARAM::AirportKernelP4, PARAM::AirportKernelScale, PARAM::AirportKernelShape, PARAM::AirportKernelType, PARAM::AirportTrafficScale, asin2sqx, PARAM::BitmapAspectScale, PARAM::BitmapMovieFrame, PARAM::BitmapScale, PARAM::BoundingBox, PARAM::CaseAbsentChildAgeCutoff, PARAM::CaseAbsentChildPropAdultCarers, PARAM::CaseAbsenteeismDelay, PARAM::CaseAbsenteeismDuration, PARAM::CaseIsolation_CellIncThresh, PARAM::CaseIsolationDelay, ADMINUNIT::CaseIsolationDelay, PARAM::CaseIsolationDuration, ADMINUNIT::CaseIsolationDuration, PARAM::CaseIsolationEffectiveness, PARAM::CaseIsolationHouseEffectiveness, PARAM::CaseIsolationPolicyDuration, PARAM::CaseIsolationProp, PARAM::CaseIsolationTimeStartBase, CDF_RES, PARAM::CFR_Critical_ByAge, PARAM::CFR_SARI_ByAge, PARAM::ClusterDigitalContactUsers, ADMINUNIT::cnt_name, PARAM::ColourPeriod, cosx, PARAM::CountryDivisor, PARAM::CriticalToCritRecov_icdf, PARAM::CriticalToDeath_icdf, PARAM::CritRecovToRecov_icdf, PARAM::cwidth, DAYS_PER_YEAR, PARAM::DigitalContactTracing_CellIncThresh, PARAM::DigitalContactTracingDelay, PARAM::DigitalContactTracingPolicyDuration, PARAM::DigitalContactTracingTimeStartBase, PARAM::DoAdminTriggers, PARAM::DoAdunitBoundaries, PARAM::DoAdunitBoundaryOutput, PARAM::DoAdunitOutput, PARAM::DoAdUnits, PARAM::DoAge, PARAM::DoAirports, PARAM::DoAllInitialInfectioninSameLoc, PARAM::DoBlanketMoveRestr, PARAM::DoCorrectAdunitPop, PARAM::DoCorrectAgeDist, PARAM::DoDeath, PARAM::DoDigitalContactTracing, PARAM::DoEarlyCaseDiagnosis, PARAM::DoGlobalTriggers, PARAM::DoHolidays, PARAM::DoHouseholds, PARAM::DoHQretrigger, PARAM::DoICUTriggers, PARAM::DoImmuneBitmap, PARAM::DoImportsViaAirports, PARAM::DoInfectionTree, PARAM::DoInfectiousnessProfile, PARAM::DoInterventionDelaysByAdUnit, PARAM::DoLatent, PARAM::DoMassVacc, PARAM::DoMoveRestrOnceOnly, PARAM::DoOneGen, PARAM::DoOriginDestinationMatrix, PARAM::DoOutputPlaceDistForOneAdunit, PARAM::DoPerCapitaTriggers, PARAM::DoPeriodicBoundaries, PARAM::DoPlaceCloseOnceOnly, PARAM::DoPlaceGroupTreat, PARAM::DoPlaces, PARAM::DoRandomInitialInfectionLoc, PARAM::DoRealSymptWithdrawal, PARAM::DoRecordInfEvents, PARAM::DoSeasonality, PARAM::DoSeverity, PARAM::DoSI, PARAM::DoSIS, PARAM::DoSocDistOnceOnly, PARAM::DoSpatial, PARAM::DoSpecifyPop, PARAM::DoSymptoms, PARAM::DoUTM_coords, PARAM::DoWholeHouseholdImmunity, PARAM::DurImportTimeProfile, ERR_CRITICAL, PARAM::ESocDistHouseholdEffect, PARAM::ESocDistHouseholdEffect2, PARAM::ESocDistPlaceEffect, PARAM::ESocDistPlaceEffect2, PARAM::ESocDistSpatialEffect, PARAM::ESocDistSpatialEffect2, PARAM::ESocProportionCompliant, PARAM::FalsePositiveAgeRate, PARAM::FalsePositivePerCapitaIncidence, PARAM::FalsePositiveRate, GetInputParameter, GetInputParameter2, PARAM::GlobalIncThreshPop, PARAM::HHQuar_CellIncThresh, PARAM::HolidayDuration, PARAM::HolidayEffect, PARAM::HolidayStartTime, PARAM::HotelPropLocal, PARAM::HouseholdDenomLookup, PARAM::HouseholdSizeDistrib, PARAM::HouseholdTrans, PARAM::HouseholdTransPow, ADMINUNIT::HQuarantineDelay, ADMINUNIT::HQuarantineDuration, PARAM::HQuarantineHouseDelay, PARAM::HQuarantineHouseDuration, PARAM::HQuarantineHouseEffect, PARAM::HQuarantinePlaceEffect, PARAM::HQuarantinePolicyDuration, PARAM::HQuarantinePropHouseCompliant, PARAM::HQuarantinePropIndivCompliant, PARAM::HQuarantineSpatialEffect, PARAM::HQuarantineTimeStartBase, ADMINUNIT::id, PARAM::ILIToRecovery_icdf, PARAM::ILIToSARI_icdf, PARAM::ImportInfectionTimeProfile, PARAM::IncThreshPop, PARAM::InfectionImportChangeTime, PARAM::InfectionImportRate1, PARAM::InfectionImportRate2, PARAM::infectious_icdf, PARAM::infectious_prof, PARAM::infectiousness, PARAM::InfectiousnessGamA, PARAM::InfectiousnessGamR, PARAM::InfectiousnessSD, PARAM::InfectiousPeriod, INFPROF_RES, PARAM::InhibitInterAdunitPlaceAssignment, PARAM::InitialImmunity, PARAM::InitialInfectionsAdminUnit, PARAM::InitialInfectionsAdminUnitId, PARAM::InitialInfectionsAdminUnitWeight, PARAM::InvJourneyDurationDistrib, PARAM::InvLocalJourneyDurationDistrib, PARAM::JourneyDurationDistrib, PARAM::KeepSameSeeds, PARAM::KernelOffsetScale, PARAM::KernelPowerScale, PARAM::KeyWorkerHouseProp, PARAM::KeyWorkerPlaceNum, PARAM::KeyWorkerPopNum, PARAM::KeyWorkerProphCellIncThresh, PARAM::KeyWorkerProphDuration, PARAM::KeyWorkerProphRadius, PARAM::KeyWorkerProphRadius2, PARAM::KeyWorkerProphRenewalDuration, PARAM::KeyWorkerProphTimeStartBase, PARAM::KeyWorkerPropInKeyPlaces, PARAM::latent_icdf, PARAM::LatentPeriod, PARAM::LatentToSymptDelay, PARAM::LengthDigitalContactIsolation, PARAM::LimitNumInfections, PARAM::LocalJourneyDurationDistrib, PARAM::LocationInitialInfection, MAX_ADUNITS, MAX_COUNTRIES, MAX_DUR_IMPORT_PROFILE, MAX_HOUSEHOLD_SIZE, MAX_INFECTIOUS_STEPS, MAX_NUM_SEED_LOCATIONS, MAX_TRAVEL_TIME, PARAM::MaxCorrSample, PARAM::MaxInfEvents, PARAM::MaxNumInfections, PARAM::MaxPopDensForInitialInfection, PARAM::Mean_CriticalToCritRecov, PARAM::Mean_CriticalToDeath, PARAM::Mean_CritRecovToRecov, PARAM::Mean_ILIToRecovery, PARAM::Mean_ILIToSARI, PARAM::Mean_MildToRecovery, PARAM::Mean_SARIToCritical, PARAM::Mean_SARIToRecovery, PARAM::MeanJourneyTime, PARAM::MeanLocalJourneyTime, PARAM::MildToRecovery_icdf, PARAM::MinPopDensForInitialInfection, PARAM::MoveDelayMean, PARAM::MoveKernelP3, PARAM::MoveKernelP4, PARAM::MoveKernelScale, PARAM::MoveKernelShape, PARAM::MoveKernelType, PARAM::MoveRestrAdminUnitDivisor, PARAM::MoveRestrByAdminUnit, PARAM::MoveRestrCellIncThresh, PARAM::MoveRestrDuration, PARAM::MoveRestrEffect, PARAM::MoveRestrRadius, PARAM::MoveRestrRadius2, PARAM::MoveRestrTimeStartBase, PARAM::N, PARAM::NC, PARAM::NDigitalContactUsers, PARAM::NDigitalHouseholdUsers, PARAM::NMCL, PARAM::NR, PARAM::NRN, NUM_AGE_GROUPS, NUM_PLACE_TYPES, PARAM::NumAdunits, PARAM::NumHolidays, PARAM::NumInitialInfections, PARAM::NumSamples, PARAM::NumSeedLocations, PARAM::OuptutNonSummaryResults, PARAM::OutputAdUnitVar, PARAM::OutputAge, PARAM::OutputBitmap, PARAM::OutputBitmapDetected, PARAM::OutputControls, PARAM::OutputCountry, PARAM::OutputDigitalContactTracing, PARAM::OutputEveryRealisation, PARAM::OutputHousehold, PARAM::OutputInfType, PARAM::OutputNonSeverity, PARAM::OutputOnlyNonExtinct, PARAM::OutputPlaceDistAdunit, PARAM::OutputR0, PARAM::OutputSeverityAdminUnit, PI, PARAM::PlaceCloseAdminUnitDivisor, PARAM::PlaceCloseAdunitPlaceTypes, PARAM::PlaceCloseAdunitPropThresh, PARAM::PlaceCloseByAdminUnit, PARAM::PlaceCloseCasePropThresh, PARAM::PlaceCloseCellIncStopThresh, PARAM::PlaceCloseCellIncThresh, ADMINUNIT::PlaceCloseDelay, PARAM::PlaceCloseDelayMean, ADMINUNIT::PlaceCloseDuration, PARAM::PlaceCloseDuration2, PARAM::PlaceCloseDurationBase, PARAM::PlaceCloseEffect, PARAM::PlaceCloseFracIncTrig, PARAM::PlaceCloseHouseholdRelContact, PARAM::PlaceCloseIncTrig, PARAM::PlaceCloseRadius, PARAM::PlaceCloseRadius2, PARAM::PlaceCloseSpatialRelContact, PARAM::PlaceCloseTimeStartBase, PARAM::PlaceCloseTimeStartBase2, PARAM::PlaceExclusivityMatrix, PARAM::PlaceTypeAgeMax, PARAM::PlaceTypeAgeMax2, PARAM::PlaceTypeAgeMax3, PARAM::PlaceTypeAgeMin, PARAM::PlaceTypeAgeMin2, PARAM::PlaceTypeAgeMin3, PARAM::PlaceTypeGroupSizeParam1, PARAM::PlaceTypeKernelP3, PARAM::PlaceTypeKernelP4, PARAM::PlaceTypeKernelScale, PARAM::PlaceTypeKernelShape, PARAM::PlaceTypeKernelType, PARAM::PlaceTypeMeanSize, PARAM::PlaceTypeNearestNeighb, PARAM::PlaceTypeNum, PARAM::PlaceTypePropAgeGroup, PARAM::PlaceTypePropAgeGroup2, PARAM::PlaceTypePropAgeGroup3, PARAM::PlaceTypePropBetweenGroupLinks, PARAM::PlaceTypeSizeMax, PARAM::PlaceTypeSizeOffset, PARAM::PlaceTypeSizePower, PARAM::PlaceTypeSizeSD, PARAM::PlaceTypeTrans, PARAM::PostAlertControlPropCasesId, PARAM::PreAlertControlPropCasesId, PARAM::PreControlClusterIdCalTime, PARAM::PreControlClusterIdCaseThreshold, PARAM::PreControlClusterIdDuration, PARAM::PreControlClusterIdHolOffset, PARAM::PreControlClusterIdTime, PARAM::PreControlClusterIdUseDeaths, PARAM::Prop_Critical_ByAge, PARAM::Prop_ILI_ByAge, PARAM::Prop_Mild_ByAge, PARAM::Prop_SARI_ByAge, PARAM::PropAgeGroup, PARAM::ProportionDigitalContactsIsolate, PARAM::ProportionSmartphoneUsersByAge, PARAM::ProportionSymptomatic, PARAM::PropPopUsingDigitalContactTracing, PARAM::R0, PARAM::R0DensityScalePower, PARAM::RecordInfEventsPerRun, PARAM::RelativeSpatialContact, PARAM::RelativeTravelRate, PARAM::ResetSeeds, PARAM::ResetSeedsPostIntervention, PARAM::SampleStep, PARAM::SampleTime, PARAM::SARIToCritical_icdf, PARAM::SARIToRecovery_icdf, PARAM::ScalingFactorPlaceDigitalContacts, PARAM::ScalingFactorSpatialDigitalContacts, PARAM::Seasonality, sinx, PARAM::SmallEpidemicCases, PARAM::SocDistCellIncStopThresh, PARAM::SocDistCellIncThresh, PARAM::SocDistChangeDelay, PARAM::SocDistDuration, PARAM::SocDistHouseholdEffect, PARAM::SocDistHouseholdEffect2, PARAM::SocDistPlaceEffect, PARAM::SocDistPlaceEffect2, PARAM::SocDistRadius, PARAM::SocDistRadius2, PARAM::SocDistSpatialEffect, PARAM::SocDistSpatialEffect2, PARAM::SocDistTimeStartBase, ADMINUNIT::SocialDistanceDelay, ADMINUNIT::SocialDistanceDuration, PARAM::SpatialBoundingBox, PARAM::SuscReductionFactorPerInfection, PARAM::SymptInfectiousness, PARAM::SymptPlaceTypeContactRate, PARAM::SymptPlaceTypeWithdrawalProp, PARAM::SymptSpatialContactRate, PARAM::TimeStep, PARAM::TimeStepsPerDay, PARAM::TimeStepsPerDayInt, PARAM::TimeStepsPerYear, PARAM::TimeToResetSeeds, PARAM::TreatAdminUnitDivisor, PARAM::TreatByAdminUnit, PARAM::TreatCaseCourseLength, PARAM::TreatCellIncThresh, PARAM::TreatDeathDrop, PARAM::TreatDelayMean, PARAM::TreatHouseholdsDuration, PARAM::TreatInfDrop, PARAM::TreatMaxCoursesBase, PARAM::TreatMaxCoursesPerCase, PARAM::TreatNewCoursesRate, PARAM::TreatNewCoursesStartTime, PARAM::TreatPlaceGeogDuration, PARAM::TreatPlaceProbCaseId, PARAM::TreatPlaceTotalProp, PARAM::TreatPropCaseHouseholds, PARAM::TreatPropCases, PARAM::TreatProphCourseLength, PARAM::TreatPropRadial, PARAM::TreatRadius, PARAM::TreatRadius2, PARAM::TreatSuscDrop, PARAM::TreatSympDrop, PARAM::TreatTimeStartBase, PARAM::TriggersSamplingInterval, PARAM::UpdatesPerSample, PARAM::usCaseAbsenteeismDelay, PARAM::usCaseAbsenteeismDuration, PARAM::usCaseIsolationDelay, PARAM::usCaseIsolationDuration, PARAM::usHQuarantineHouseDuration, PARAM::usVaccTimeEfficacySwitch, PARAM::usVaccTimeToEfficacy, PARAM::VaccAdminUnitDivisor, PARAM::VaccByAdminUnit, PARAM::VaccCampaignInterval, PARAM::VaccCellIncThresh, PARAM::VaccCoverageIncreasePeriod, PARAM::VaccDelayMean, PARAM::VaccDosePerDay, PARAM::VaccEfficacyDecay, PARAM::VaccHouseholdsDuration, PARAM::VaccInfDrop, PARAM::VaccMaxCoursesBase, PARAM::VaccMaxRounds, PARAM::VaccMinRadius, PARAM::VaccMinRadius2, PARAM::VaccMortDrop, PARAM::VaccNewCoursesEndTime, PARAM::VaccNewCoursesRate, PARAM::VaccNewCoursesStartTime, PARAM::VaccPriorityGroupAge, PARAM::VaccProp, PARAM::VaccPropCaseHouseholds, PARAM::VaccRadius, PARAM::VaccRadius2, PARAM::VaccSuscDrop, PARAM::VaccSuscDrop2, PARAM::VaccSympDrop, PARAM::VaccTimeEfficacySwitch, PARAM::VaccTimeStartBase, PARAM::VaccTimeStartGeo, PARAM::VaccTimeToEfficacy, PARAM::WAIFW_Matrix.
Referenced by main.
void ReadInterventions(char *)
References PARAM::AdunitLevel1Divisor, PARAM::AdunitLevel1Lookup, PARAM::AdunitLevel1Mask, INTERVENTION::ControlParam, DAYS_PER_YEAR, INTERVENTION::DoAUThresh, ERR_CRITICAL, GetXMLNode, ADMINUNIT::id, ADMINUNIT::InterventionList, INTERVENTION::InterventionType, INTERVENTION::Level, INTERVENTION::LevelAUVar, INTERVENTION::LevelCellVar, INTERVENTION::LevelClustering, INTERVENTION::LevelCountryVar, INTERVENTION::MaxResource, INTERVENTION::MaxRounds, INTERVENTION::MinDuration, ADMINUNIT::NI, INTERVENTION::NoStartAfterMin, PARAM::NumAdunits, ranf, INTERVENTION::RepeatInterval, INTERVENTION::StartThresholdHigh, INTERVENTION::StartThresholdLow, INTERVENTION::StartTime, INTERVENTION::StopThreshold, INTERVENTION::StopTime, INTERVENTION::TimeOffset.
Referenced by main.
int GetXMLNode(FILE *, const char *, const char *, char *, int)
References ERR_CRITICAL.
Referenced by ReadInterventions.
void ReadAirTravel(char *)
References PARAM::Air_popscale, PARAM::AirportTrafficScale, AirTravelDist, AIRPORT::conn_airports, dist2_raw, ERR_CRITICAL, AIRPORT::Inv_prop_traffic, AIRPORT::loc_x, AIRPORT::loc_y, MAX_AIRPORTS, MAX_DIST, PARAM::N, PARAM::Nairports, AIRPORT::num_connected, OutFile, OUTPUT_DIST_SCALE, AIRPORT::prop_traffic, PARAM::SpatialBoundingBox, AIRPORT::total_traffic.
Referenced by main.
void InitModel(int)
References PERSON::absent_start_time, PERSON::absent_stop_time, PARAM::AirportCloseTimeStart, bmi2, bmi3, bmi4, ADMINUNIT::caseDetectInit, ADMINUNIT::caseDetectRate, PARAM::CaseIsolationTimeStart, ADMINUNIT::CaseIsolationTimeStart, PLACE::close_end_time, PLACE::close_start_time, PLACE::control_trig, PARAM::ControlPropCasesId, POPVAR::Critical, POPVAR::Critical_adunit, PERSON::Critical_time, POPVAR::CritRecov, POPVAR::CritRecov_adunit, POPVAR::cumAA, POPVAR::cumAC, POPVAR::cumACS, POPVAR::cumAH, POPVAR::cumAPA, POPVAR::cumAPC, POPVAR::cumAPCS, POPVAR::cumC, POPVAR::cumC_adunit, POPVAR::cumC_country, POPVAR::cumC_keyworker, POPVAR::cumCa, POPVAR::cumCC, POPVAR::cumCC_adunit, POPVAR::cumCritical, POPVAR::cumCritical_adunit, POPVAR::cumCritRecov, POPVAR::cumCritRecov_adunit, POPVAR::cumCT, POPVAR::cumCT_adunit, POPVAR::cumD, POPVAR::cumD_adunit, POPVAR::cumDa, POPVAR::cumDC, POPVAR::cumDC_adunit, POPVAR::cumDCT, POPVAR::cumDCT_adunit, POPVAR::cumFC, POPVAR::cumH, POPVAR::cumH_adunit, POPVAR::cumHQ, POPVAR::cumI, POPVAR::cumI_adunit, POPVAR::cumI_keyworker, POPVAR::cumIa, POPVAR::cumILI, POPVAR::cumILI_adunit, POPVAR::cumInf_h, POPVAR::cumInf_n, POPVAR::cumInf_s, POPVAR::cumItype, POPVAR::cumMild, POPVAR::cumMild_adunit, POPVAR::cumR, POPVAR::cumSARI, POPVAR::cumSARI_adunit, POPVAR::cumT, POPVAR::cumT_adunit, POPVAR::cumT_keyworker, POPVAR::cumTC, CELL::cumTC, POPVAR::cumTP, POPVAR::cumUT, POPVAR::cumV, POPVAR::cumV_daily, POPVAR::cumVG, POPVAR::D, CELL::D, POPVAR::DCT, POPVAR::DCT_adunit, PERSON::dct_start_time, PERSON::detected, ADMINUNIT::DigitalContactTracingTimeStart, PARAM::DoAdUnits, PARAM::DoAirports, DoImmune, PARAM::DoInitEquilib, DoInitUpdateProbs, PARAM::DoPlaces, PARAM::DoRecordInfEvents, PARAM::DoSeverity, PARAM::DoSIS, PARAM::DoUpdateCaseDetection, PARAM::DoWholeHouseholdImmunity, PARAM::ESocDistHouseholdEffect, PARAM::ESocDistHouseholdEffectC, PARAM::ESocDistPlaceEffect, PARAM::ESocDistPlaceEffectC, PARAM::ESocDistSpatialEffect, PARAM::ESocDistSpatialEffectC, PERSON::hh, HOST_AGE_GROUP, HOST_AGE_YEAR, HOTEL_PLACE_TYPE, PARAM::HQuarantineTimeStart, ADMINUNIT::HQuarantineTimeStart, POPVAR::I, CELL::I, POPVAR::ILI, POPVAR::ILI_adunit, BITMAP_HEADER::imagesize, PERSON::inf, PERSON::infect_type, INFECT_TYPE_MASK, CELL::infected, EVENTS::infectee_adunit, EVENTS::infectee_cell, EVENTS::infectee_ind, EVENTS::infectee_x, EVENTS::infectee_y, PERSON::infector, EVENTS::infector_cell, EVENTS::infector_ind, InfStat_Susceptible, PARAM::InitialImmunity, PARAM::InitialInfectionsAdminUnitWeight, PERSON::isolation_start_time, MICROCELL::keyworkerproph, MICROCELL::keyworkerproph_end_time, MICROCELL::keyworkerproph_trig, PARAM::KeyWorkerProphTimeStart, POPVAR::L, CELL::L, CELL::latent, PERSON::latent_time, PERSON::listpos, EVENTS::listpos, MAX_COUNTRIES, MAX_INTERVENTION_TYPES, MAX_NUM_SEED_LOCATIONS, MAX_NUM_THREADS, PARAM::MaxInfEvents, POPVAR::maxRad2, PARAM::MeanAnnualDeathRate, CELL::members, POPVAR::Mild, POPVAR::Mild_adunit, MICROCELL::move_end_time, MICROCELL::move_start_time, MICROCELL::move_trig, MICROCELL::moverest, PARAM::MoveRestrTimeStart, POPVAR::mvacc_cum, PARAM::N, CELL::n, PARAM::NC, PERSON::ncontacts, ADMINUNIT::ndct, ADMINUNIT::ndct_queue, nEvents, HOUSEHOLD::nh, PARAM::NMCP, MICROCELL::np, ns, NUM_AGE_GROUPS, NUM_PLACE_TYPES, PERSON::num_treats, PARAM::NumAdunits, PARAM::NumInitialInfections, POPVAR::NumPlacesClosed, PARAM::NumSeedLocations, PARAM::NumThreads, PARAM::OutputBitmap, ADMINUNIT::place_close_trig, MICROCELL::place_end_time, MICROCELL::place_trig, MICROCELL::placeclose, PARAM::PlaceCloseDuration, PARAM::PlaceCloseDurationBase, PARAM::PlaceCloseTimeStart, ADMINUNIT::PlaceCloseTimeStart, PARAM::PlaceCloseTimeStart2, PERSON::PlaceLinks, MICROCELL::places, PARAM::PlaceTypeNum, PARAM::PreAlertControlPropCasesId, PERSON::quar_comply, PERSON::quar_start_time, POPVAR::R, CELL::R, ranf_mt, PARAM::RecordInfEventsPerRun, PERSON::RecoveringFromCritical_time, PERSON::recovery_time, PARAM::ResetSeedsFlag, POPVAR::S, CELL::S, POPVAR::SARI, POPVAR::SARI_adunit, PERSON::SARI_time, SeedInfection, Severity_Asymptomatic, PERSON::Severity_Current, PERSON::Severity_Final, MICROCELL::socdist, MICROCELL::socdist_end_time, MICROCELL::socdist_trig, PARAM::SocDistDuration, PARAM::SocDistDurationC, PARAM::SocDistHouseholdEffect, PARAM::SocDistHouseholdEffectC, PARAM::SocDistPlaceEffect, PARAM::SocDistPlaceEffectC, PARAM::SocDistSpatialEffect, PARAM::SocDistSpatialEffectC, PARAM::SocDistTimeStart, ADMINUNIT::SocialDistanceTimeStart, POPVAR::sumRad2, PERSON::susc, CELL::susceptible, PARAM::SuscReductionFactorPerInfection, EVENTS::t, EVENTS::t_infector, EVENTS::thread, PERSON::to_die, CELL::tot_treat, CELL::tot_vacc, PERSON::Travelling, MICROCELL::treat, PLACE::treat, MICROCELL::treat_end_time, PLACE::treat_end_time, PERSON::treat_start_time, MICROCELL::treat_start_time, PERSON::treat_stop_time, MICROCELL::treat_trig, PARAM::TreatMaxCourses, PARAM::TreatMaxCoursesBase, PARAM::TreatTimeStart, POPVAR::trigDC, POPVAR::trigDC_adunit, UpdateProbs, MICROCELL::vacc, PERSON::vacc_start_time, MICROCELL::vacc_start_time, MICROCELL::vacc_trig, PARAM::VaccMaxCourses, PARAM::VaccMaxCoursesBase, PARAM::VaccTimeStart.
Referenced by main.
void SeedInfection(double, int *, int, int)
References PARAM::AdunitLevel1Divisor, PARAM::AdunitLevel1Mask, CalcPersonSusc, PARAM::DoAllInitialInfectioninSameLoc, PARAM::DoImportsViaAirports, DoInfect, PARAM::DoRandomInitialInfectionLoc, PERSON::hh, PERSON::infect_type, INFECT_TYPE_MASK, PERSON::infector, InfStat_Susceptible, PARAM::InitialInfectionsAdminUnit, HOUSEHOLD::loc_x, HOUSEHOLD::loc_y, PARAM::LocationInitialInfection, PARAM::MaxPopDensForInitialInfection, PERSON::mcell, PARAM::mcheight, PARAM::mcwidth, MICROCELL::members, PARAM::MinPopDensForInitialInfection, PARAM::N, MICROCELL::n, PARAM::nmch, PARAM::NumSeedLocations, ranf.
Referenced by InitModel, RunModel.
int RunModel(int)
References POPVAR::cumD, POPVAR::cumI, POPVAR::cumT, POPVAR::cumV, POPVAR::cumVG, POPVAR::D, DigitalContactTracingSweep, PARAM::DoAirports, PARAM::DoDeath, PARAM::DoDigitalContactTracing, DoFalseCase, DoInitUpdateProbs, PARAM::DoLoadSnapshot, PARAM::DoSaveSnapshot, PARAM::DoSI, PARAM::DoSIS, PARAM::DurImportTimeProfile, PARAM::FalsePositiveAgeRate, PARAM::FalsePositivePerCapitaIncidence, HOST_AGE_GROUP, POPVAR::I, ignpoi, PARAM::ImportInfectionTimeProfile, IncubRecoverySweep, PARAM::InfectionImportChangeTime, PARAM::InfectionImportRate1, PARAM::InfectionImportRate2, InfectSweep, InfStat_Dead, PARAM::InitialInfectionsAdminUnitWeight, InterruptRun, POPVAR::L, PARAM::LimitNumInfections, MAX_NUM_SEED_LOCATIONS, MAX_TRAVEL_TIME, PARAM::MaxNumInfections, POPVAR::maxRad2, PARAM::N, PARAM::newseed1, PARAM::newseed2, ns, PARAM::NumSamples, PARAM::NumSeedLocations, POPVAR::R, ranf, RecordInfTypes, RecordSample, PARAM::ResetSeedsFlag, PARAM::ResetSeedsPostIntervention, POPVAR::S, PARAM::SampleStep, PARAM::SampleTime, SaveSnapshot, SeedInfection, setall, PARAM::SnapshotLoadTime, PARAM::SnapshotSaveTime, PARAM::TimeStep, PARAM::TimeStepsPerDay, PARAM::TimeToResetSeeds, TravelDepartSweep, TravelReturnSweep, PARAM::TreatMaxCourses, PARAM::TreatNewCoursesRate, PARAM::TreatNewCoursesStartTime, TreatSweep, PARAM::ts_age, UpdateProbs, PARAM::UpdatesPerSample, PARAM::VaccMaxCourses, PARAM::VaccNewCoursesEndTime, PARAM::VaccNewCoursesRate, PARAM::VaccNewCoursesStartTime.
Referenced by main.
void TravelReturnSweep(double)
Referenced by RunModel.
void TravelDepartSweep(double)
Referenced by RunModel.
void InfectSweep(double, int)
Referenced by RunModel.
void IncubRecoverySweep(double, int)
Referenced by RunModel.
int TreatSweep(double)
Referenced by RunModel.
void DigitalContactTracingSweep(double)
Referenced by RunModel.
void SaveDistribs(void)
References MICROCELL::adunit, PARAM::AdunitLevel1Divisor, PARAM::AdunitLevel1Mask, dist2_raw, PARAM::DoOutputPlaceDistForOneAdunit, PARAM::DoPlaces, ERR_CRITICAL, HOTEL_PLACE_TYPE, ADMINUNIT::id, MAX_DIST, MAX_PLACE_SIZE, PERSON::mcell, PARAM::N, PLACE::n, PARAM::Nplace, OutFile, OUTPUT_DIST_SCALE, PARAM::OutputPlaceDistAdunit, PlaceDistDistrib, PERSON::PlaceLinks, PlaceSizeDistrib, PARAM::PlaceTypeNum.
void SaveOriginDestMatrix(void)
References PARAM::AdunitLevel1Divisor, PARAM::AdunitLevel1Mask, ERR_CRITICAL, PARAM::NumAdunits, OutFile.
Referenced by main.
void SaveResults(void)
References PARAM::AdunitLevel1Divisor, PARAM::AdunitLevel1Mask, DIRECTORY_SEPARATOR, PARAM::DoAdunitOutput, PARAM::DoAdUnits, PARAM::DoDigitalContactTracing, PARAM::DoInfectionTree, ERR_CRITICAL, HOST_AGE_YEAR, INFECT_TYPE_MASK, PARAM::KeyWorkerIncHouseNum, PARAM::KeyWorkerNum, PARAM::KeyWorkerProphTimeStartBase, PARAM::N, PARAM::NumAdunits, PARAM::NumSamples, OutFile, PARAM::OutputBitmap, PARAM::OutputDigitalContactTracing, PARAM::OutputNonSeverity, PARAM::SampleStep, PARAM::SampleTime, PARAM::SpatialBoundingBox.
Referenced by main.
void SaveSummaryResults(void)
References AGE_GROUP_WIDTH, AgeDist, case_household_av, denom_household, PARAM::DoAdunitOutput, PARAM::DoAdUnits, PARAM::DoSeverity, ERR_CRITICAL, indivR0_av, inf_household_av, infcountry_av, infcountry_num, INFECT_TYPE_MASK, PARAM::KeyWorkerIncHouseNum, PARAM::KeyWorkerNum, PARAM::KeyWorkerProphTimeStartBase, MAX_COUNTRIES, MAX_GEN_REC, MAX_HOUSEHOLD_SIZE, MAX_SEC_REC, PARAM::NRactE, PARAM::NRactNE, PARAM::NRactual, NUM_AGE_GROUPS, NUM_PLACE_TYPES, PARAM::NumAdunits, PARAM::NumSamples, OutFile, PARAM::OutputAdUnitVar, PARAM::OutputAge, PARAM::OutputControls, PARAM::OutputCountry, PARAM::OutputHousehold, PARAM::OutputInfType, PARAM::OutputNonSeverity, PARAM::OutputR0, PARAM::OutputSeverityAdminUnit, PeakHeightSS, PeakHeightSum, PeakTimeSS, PeakTimeSum, PARAM::PopByAdunit, PARAM::R0household, PARAM::R0places, PARAM::R0spatial, PARAM::SampleTime.
Referenced by main.
void SaveRandomSeeds(void)
References ERR_CRITICAL, PARAM::newseed1, PARAM::newseed2, OutFile.
Referenced by main.
void SaveEvents(void)
References ERR_CRITICAL, nEvents, OutFile.
Referenced by main.
void LoadSnapshot(void)
References POPVAR::CellMemberArray, POPVAR::CellSuscMemberArray, CELL::cum_trans, ERR_CRITICAL, ERR_CRITICAL_FMT, fread_big, CELL::infected, CELL::InvCDF, CELL::latent, MAX_INTERVENTION_TYPES, CELL::max_trans, MICROCELL::members, CELL::members, PARAM::N, PARAM::NC, PARAM::nch, PARAM::NCP, PARAM::ncw, PARAM::NH, PARAM::NMC, PARAM::NumSamples, PARAM::SampleStep, PARAM::SampleTime, PARAM::seed1, PARAM::seed2, SnapshotLoadFile, PARAM::SnapshotLoadTime, CELL::susceptible, PARAM::TimeStep, CELL::tot_prob, zfread_big.
Referenced by main.
void SaveSnapshot(void)
References POPVAR::CellMemberArray, POPVAR::CellSuscMemberArray, ERR_CRITICAL, fwrite_big, PARAM::N, PARAM::NC, PARAM::nch, PARAM::NCP, PARAM::ncw, PARAM::NH, PARAM::NMC, PARAM::seed1, PARAM::seed2, SnapshotSaveFile, PARAM::SnapshotSaveTime, PARAM::TimeStep, zfwrite_big.
Referenced by RunModel.
void RecordInfTypes(void)
References case_household, case_household_av, MICROCELL::country, RESULTS::cumT, RESULTS::cumTmax, RESULTS::cumV, RESULTS::cumVmax, PARAM::DoAdUnits, RESULTS::extinct, PERSON::hh, HOST_AGE_GROUP, RESULTS::incC, indivR0, indivR0_av, inf_household, inf_household_av, infcountry, infcountry_av, infcountry_num, PERSON::infect_type, INFECT_TYPE_MASK, InfStat_Dead, InfStat_Dead_WasSymp, InfStat_ImmuneAtStart, InfStat_Recovered, InfStat_RecoveredFromSymp, InfStat_Susceptible, inftype, inftype_av, PERSON::listpos, MAX_ADUNITS, MAX_COUNTRIES, MAX_GEN_REC, MAX_HOUSEHOLD_SIZE, MAX_SEC_REC, PERSON::mcell, CELL::members, PARAM::N, CELL::n, PARAM::NC, HOUSEHOLD::nh, PARAM::NRactE, PARAM::NRactNE, NUM_AGE_GROUPS, PARAM::NumSamples, PeakHeightSS, PeakHeightSum, PeakTimeSS, PeakTimeSum, PARAM::PreControlClusterIdTime, RESULTS::Rage, RESULTS::Rdenom, RESULTS::Rtype, PARAM::SampleStep, PARAM::SampleTime, RESULTS::t, PARAM::TimeStep, TSMeanE, TSMeanNE, TSVarE, TSVarNE.
Referenced by RunModel.
void RecordSample(double, int)
References PARAM::AirportCloseTimeStart, PARAM::AirportCloseTimeStartBase, CaptureBitmap, PARAM::CaseIsolation_CellIncThresh, PARAM::CaseIsolationTimeStartBase, ChooseThreshold, ChooseTriggerVariableAndValue, PARAM::ControlPropCasesId, POPVAR::Critical, RESULTS::Critical, POPVAR::Critical_adunit, RESULTS::Critical_adunit, POPVAR::CritRecov, RESULTS::CritRecov, POPVAR::CritRecov_adunit, RESULTS::CritRecov_adunit, POPVAR::cumAA, POPVAR::cumAC, POPVAR::cumACS, POPVAR::cumAH, POPVAR::cumAPA, POPVAR::cumAPC, POPVAR::cumAPCS, POPVAR::cumC, POPVAR::cumC_adunit, POPVAR::cumC_country, POPVAR::cumC_keyworker, POPVAR::cumCC, POPVAR::cumCC_adunit, POPVAR::cumCritical, RESULTS::cumCritical, POPVAR::cumCritical_adunit, RESULTS::cumCritical_adunit, POPVAR::cumCritRecov, RESULTS::cumCritRecov, POPVAR::cumCritRecov_adunit, RESULTS::cumCritRecov_adunit, POPVAR::cumCT, POPVAR::cumCT_adunit, POPVAR::cumD, POPVAR::cumD_adunit, RESULTS::cumD_adunit, POPVAR::cumDC, RESULTS::cumDC, POPVAR::cumDC_adunit, POPVAR::cumDCT, POPVAR::cumDCT_adunit, POPVAR::cumFC, POPVAR::cumH, POPVAR::cumH_adunit, POPVAR::cumHQ, POPVAR::cumI, POPVAR::cumI_adunit, POPVAR::cumI_keyworker, POPVAR::cumILI, RESULTS::cumILI, POPVAR::cumILI_adunit, RESULTS::cumILI_adunit, POPVAR::cumItype, POPVAR::cumMild, RESULTS::cumMild, POPVAR::cumMild_adunit, RESULTS::cumMild_adunit, POPVAR::cumR, POPVAR::cumSARI, RESULTS::cumSARI, POPVAR::cumSARI_adunit, RESULTS::cumSARI_adunit, POPVAR::cumT, RESULTS::cumT, RESULTS::cumT_adunit, RESULTS::cumT_keyworker, POPVAR::cumTC, CELL::cumTC, POPVAR::cumTP, RESULTS::cumTP, POPVAR::cumUT, RESULTS::cumUT, POPVAR::cumV, RESULTS::cumV, POPVAR::cumVG, RESULTS::cumVG, POPVAR::D, RESULTS::D, CELL::D, DAYS_PER_YEAR, PARAM::DigitalContactTracing_CellIncThresh, PARAM::DigitalContactTracingTimeStartBase, PARAM::DoAdUnits, PARAM::DoDigitalContactTracing, PARAM::DoGlobalTriggers, PARAM::DoICUTriggers, PARAM::DoInterventionDelaysByAdUnit, DoOrDontAmendStartTime, PARAM::DoPlaces, PARAM::DoSeverity, PARAM::ESocDistHouseholdEffect2, PARAM::ESocDistHouseholdEffectC, PARAM::ESocDistPlaceEffect2, PARAM::ESocDistPlaceEffectC, PARAM::ESocDistSpatialEffect2, PARAM::ESocDistSpatialEffectC, RESULTS::extinct, PARAM::HHQuar_CellIncThresh, PARAM::HQuarantineTimeStartBase, POPVAR::I, RESULTS::I, CELL::I, POPVAR::ILI, RESULTS::ILI, POPVAR::ILI_adunit, RESULTS::ILI_adunit, RESULTS::incAA, RESULTS::incAC, RESULTS::incACS, RESULTS::incAH, RESULTS::incAPA, RESULTS::incAPC, RESULTS::incAPCS, RESULTS::incC, RESULTS::incC_adunit, RESULTS::incC_keyworker, RESULTS::incCa, RESULTS::incCC, RESULTS::incCC_adunit, RESULTS::incCritical, RESULTS::incCritical_adunit, RESULTS::incCritRecov, RESULTS::incCritRecov_adunit, RESULTS::incCT, RESULTS::incCT_adunit, RESULTS::incD, RESULTS::incD_adunit, RESULTS::incDa, RESULTS::incDC, RESULTS::incDC_adunit, RESULTS::incDCT, RESULTS::incDCT_adunit, RESULTS::incFC, RESULTS::incH, RESULTS::incH_adunit, RESULTS::incHQ, RESULTS::incI, RESULTS::incI_adunit, RESULTS::incI_keyworker, RESULTS::incIa, RESULTS::incILI, RESULTS::incILI_adunit, RESULTS::incItype, RESULTS::incMild, RESULTS::incMild_adunit, RESULTS::incR, RESULTS::incSARI, RESULTS::incSARI_adunit, RESULTS::incTC, INFECT_TYPE_MASK, InterruptRun, PARAM::KeyWorkerProphCellIncThresh, PARAM::KeyWorkerProphTimeStart, PARAM::KeyWorkerProphTimeStartBase, POPVAR::L, RESULTS::L, CELL::L, MAX_COUNTRIES, RESULTS::maxRad, POPVAR::maxRad2, POPVAR::Mild, RESULTS::Mild, POPVAR::Mild_adunit, RESULTS::Mild_adunit, PARAM::MoveRestrCellIncThresh, PARAM::MoveRestrTimeStart, PARAM::MoveRestrTimeStartBase, PARAM::N, PARAM::NCP, ADMINUNIT::ndct, PARAM::NMC, PARAM::Nplace, NUM_AGE_GROUPS, NUM_PLACE_TYPES, PARAM::NumAdunits, POPVAR::NumPlacesClosed, PARAM::NumThreads, PARAM::OutputBitmap, OutputBitmap, PLACE_CLOSED, PARAM::PlaceCloseCellIncThresh, PARAM::PlaceCloseDuration, PARAM::PlaceCloseDuration2, PARAM::PlaceCloseIndepThresh, PARAM::PlaceCloseTimeStart, PARAM::PlaceCloseTimeStart2, PARAM::PlaceCloseTimeStartBase, PARAM::PlaceCloseTimeStartBase2, PARAM::PlaceTypeNum, PARAM::PostAlertControlPropCasesId, PARAM::PreControlClusterIdCalTime, PARAM::PreControlClusterIdCaseThreshold, PARAM::PreControlClusterIdDuration, PARAM::PreControlClusterIdHolOffset, PARAM::PreControlClusterIdTime, PARAM::PreControlClusterIdUseDeaths, RESULTS::PropPlacesClosed, RESULTS::PropSocDist, POPVAR::R, RESULTS::R, CELL::R, RESULTS::rmsRad, POPVAR::S, RESULTS::S, CELL::S, PARAM::SampleStep, POPVAR::SARI, RESULTS::SARI, POPVAR::SARI_adunit, RESULTS::SARI_adunit, PARAM::SmallEpidemicCases, PARAM::SocDistCellIncThresh, PARAM::SocDistChangeDelay, PARAM::SocDistDuration2, PARAM::SocDistDurationC, PARAM::SocDistHouseholdEffect2, PARAM::SocDistHouseholdEffectC, PARAM::SocDistPlaceEffect2, PARAM::SocDistPlaceEffectC, PARAM::SocDistSpatialEffect2, PARAM::SocDistSpatialEffectC, PARAM::SocDistTimeStart, PARAM::SocDistTimeStartBase, POPVAR::sumRad2, RESULTS::t, PARAM::TimeStepsPerDay, PARAM::TreatCellIncThresh, PARAM::TreatTimeStart, PARAM::TreatTimeStartBase, POPVAR::trigDC, POPVAR::trigDC_adunit, PARAM::TriggersSamplingInterval, TSMeanNE, TSVarNE, PARAM::VaccCellIncThresh, PARAM::VaccTimeStart, PARAM::VaccTimeStartBase.
Referenced by RunModel.
double ContactTracingEffect(int, unsigned short int)
void CalcOriginDestMatrix_adunit(void)
References MICROCELL::adunit, Cells, PARAM::CountryDivisor, ADMINUNIT::id, MAX_ADUNITS, PARAM::nch, PARAM::NCP, PARAM::nmch, PARAM::NMCL, PARAM::NumAdunits, PARAM::NumThreads, POPVAR::origin_dest, ADMINUNIT::origin_dest.
Referenced by main.
int BedsAvailablePerAdUnit(double, int)
int GetInputParameter(FILE *, FILE *, const char *, const char *, void *, int, int, int)
References ERR_CRITICAL_FMT, GetInputParameter2.
Referenced by ReadParams.
int GetInputParameter2(FILE *, FILE *, const char *, const char *, void *, int, int, int)
References GetInputParameter3.
Referenced by GetInputParameter, ReadParams.
int GetInputParameter3(FILE *, const char *, const char *, void *, int, int, int)
References PARAM::clP1, PARAM::clP2, PARAM::clP3, PARAM::clP4, PARAM::clP5, PARAM::clP6, ERR_CRITICAL_FMT, readString.
Referenced by GetInputParameter2.
int main(int argc, char *argv[])
References AdunitFile, CalcOriginDestMatrix_adunit, PARAM::clP1, PARAM::clP2, PARAM::clP3, PARAM::clP4, PARAM::clP5, PARAM::clP6, count_ranf, count_ranfmt, DIRECTORY_SEPARATOR, PARAM::DoAdunitDemog, PARAM::DoAdUnits, PARAM::DoAirports, PARAM::DoHeteroDensity, PARAM::DoInterventionFile, PARAM::DoLoadSnapshot, PARAM::DoOriginDestinationMatrix, PARAM::DoPeriodicBoundaries, PARAM::DoRecordInfEvents, PARAM::DoSaveSnapshot, PARAM::DoSchoolFile, ERR_CRITICAL, RESULTS::extinct, InitModel, InterruptRun, PARAM::KeepSameSeeds, PARAM::KernelOffsetScale, PARAM::KernelPowerScale, PARAM::LoadSaveNetwork, LoadSnapshot, m_gdiplusToken, MAX_ADUNITS, MAX_NUM_THREADS, MAXINTFILE, PARAM::MaxNumThreads, PARAM::newseed1, PARAM::newseed2, PARAM::NR, PARAM::NRactE, PARAM::NRactNE, PARAM::NRactual, PARAM::NRN, PARAM::NumSamples, PARAM::NumThreads, PARAM::OuptutNonSummaryResults, OutDensFile, OutFile, OutFileBase, PARAM::OutputDensFile, PARAM::OutputEveryRealisation, PARAM::OutputOnlyNonExtinct, PARAM::PlaceCloseIndepThresh, PARAM::PreControlClusterIdCaseThreshold, PARAM::R0scale, ranf, ReadAirTravel, ReadInterventions, ReadParams, PARAM::RecordInfEventsPerRun, PARAM::ResetSeeds, RunModel, SaveEvents, SaveOriginDestMatrix, SaveRandomSeeds, SaveResults, SaveSummaryResults, PARAM::seed1, PARAM::seed2, PARAM::seed3, PARAM::seed4, setall, SetupModel, SnapshotLoadFile, SnapshotSaveFile, PARAM::SnapshotSaveTime, TSMeanE, TSMeanNE, TSVarE, TSVarNE.
void UpdateProbs(int DoPlace)
References CELL::cum_trans, PARAM::DoDeath, PARAM::DoSIS, CELL::I, CELL::InvCDF, CELL::L, CELL::max_trans, CELL::n, PARAM::NCP, CELL::S, CELL::S0, CELL::tot_prob.
Referenced by AssignPeopleToPlaces, InitModel, RunModel, SetupModel.
int ChooseTriggerVariableAndValue(int AdUnit)
References PARAM::DoAdminTriggers, PARAM::DoGlobalTriggers, PARAM::DoPerCapitaTriggers, PARAM::GlobalIncThreshPop, PARAM::N, POPVAR::trigDC, POPVAR::trigDC_adunit.
Referenced by RecordSample.
double ChooseThreshold(int AdUnit, double WhichThreshold)
References PARAM::DoAdminTriggers, PARAM::DoGlobalTriggers, PARAM::DoPerCapitaTriggers, PARAM::IncThreshPop.
Referenced by RecordSample.
void DoOrDontAmendStartTime(double *StartTimeToAmend, double StartTime)
Referenced by RecordSample.
bool readString(const char *SItemName, FILE *dat, char *buf)
References ERR_CRITICAL_FMT.
Referenced by GetInputParameter3.