Bitmap.h
SPATIALSIM_BITMAP_H_INCLUDED_
DIRECTORY_SEPARATOR
Referenced by main, OutputBitmap, SaveResults.
WIN32_BM
STRICT
_WIN32_WINNT
WIN32_LEAN_AND_MEAN
BWCOLS
Referenced by CaptureBitmap, InitBMHead.
typedef struct BITMAP_HEADER bitmap_header
float* bmi
Referenced by CaptureBitmap, InitBMHead.
float * bmi2
Referenced by CaptureBitmap, DoDeath, DoInfect, DoRecover, InitBMHead, InitModel.
float * bmi3
Referenced by CaptureBitmap, DoDeath, DoImmune, DoRecover, InitBMHead, InitModel.
float * bmi4
Referenced by CaptureBitmap, DoProph, DoProphNoDelay, DoTreatCase, DoVacc, DoVaccNoDelay, InitBMHead, InitModel.
bitmap_header* bmh
Referenced by CaptureBitmap, DoDeath, DoImmune, DoInfect, DoProph, DoProphNoDelay, DoRecover, DoTreatCase, DoVacc, DoVaccNoDelay, InitBMHead, OutputBitmap.
ULONG_PTR m_gdiplusToken
Referenced by InitBMHead, main.
void CaptureBitmap(int, int)
References MICROCELL::adunit, PARAM::AdunitBitmapDivisor, PARAM::AdunitLevel1Mask, AdUnits, PARAM::bheight, bmh, bmi, bmi2, bmi3, bmi4, PARAM::bminx, PARAM::bminy, bmPixels, BWCOLS, PARAM::bwidth, MICROCELL::country, PARAM::DoAdunitBoundaryOutput, PERSON::hh, Hosts, Households, ADMINUNIT::id, HOUSEHOLD::loc_y, Mcells, PARAM::mcheight, PARAM::mcwidth, PARAM::N, MICROCELL::n, PARAM::NMC, PARAM::nmch, P, PARAM::scalex, PARAM::scaley, BITMAP_HEADER::width.
Referenced by RecordSample.
void OutputBitmap(double, int)
References bmf, bmh, bmpdib, bmPixels, DIRECTORY_SEPARATOR, encoderClsid, ERR_CRITICAL, ERR_CRITICAL_FMT, fwrite_big, BITMAP_HEADER::imagesize, OutFile.
Referenced by RecordSample.
void InitBMHead()
References PARAM::bheight2, bmf, bmh, bmi, bmi2, bmi3, bmi4, bmp, bmpdib, bmPixels, BITMAP_HEADER::boffset, BWCOLS, PARAM::bwidth, BITMAP_HEADER::colours, BITMAP_HEADER::compr, encoderClsid, ERR_CRITICAL, BITMAP_HEADER::filesize, BITMAP_HEADER::headersize, BITMAP_HEADER::height, BITMAP_HEADER::hres, BITMAP_HEADER::imagesize, BITMAP_HEADER::impcol, m_gdiplusToken, OutFileBase, P, BITMAP_HEADER::palette, BITMAP_HEADER::PlanesAndBitspp, BITMAP_HEADER::spare, BITMAP_HEADER::vres, BITMAP_HEADER::width.
Referenced by SetupModel.