Bitmap.cpp
ULONG_PTR m_gdiplusToken
Referenced by InitBMHead, main.
HBITMAP bmpdib
Referenced by InitBMHead, OutputBitmap.
CLSID encoderClsid
Referenced by InitBMHead, OutputBitmap.
unsigned char* bmf
Referenced by InitBMHead, OutputBitmap.
unsigned char * bmPixels
Referenced by CaptureBitmap, InitBMHead, OutputBitmap.
unsigned char * bmp
Referenced by InitBMHead.
char OutFile[1024][1024]
Referenced by OutputBitmap, SaveAgeDistrib.
char OutFileBase[1024][1024]
Referenced by InitBMHead, main.
void CaptureBitmap(int ns, int tp)
References MICROCELL::adunit, PARAM::AdunitBitmapDivisor, PARAM::AdunitLevel1Mask, AdUnits, PARAM::bheight, bmh, bmi, bmi2, bmi3, bmi4, PARAM::bminx, PARAM::bminy, bmPixels, BWCOLS, PARAM::bwidth, MICROCELL::country, PARAM::DoAdunitBoundaryOutput, PERSON::hh, Hosts, Households, ADMINUNIT::id, HOUSEHOLD::loc_y, Mcells, PARAM::mcheight, PARAM::mcwidth, PARAM::N, MICROCELL::n, PARAM::NMC, PARAM::nmch, P, PARAM::scalex, PARAM::scaley, BITMAP_HEADER::width.
Referenced by RecordSample.
void OutputBitmap(double t2, int tp)
References bmf, bmh, bmpdib, bmPixels, DIRECTORY_SEPARATOR, encoderClsid, ERR_CRITICAL, ERR_CRITICAL_FMT, fwrite_big, BITMAP_HEADER::imagesize, OutFile.
Referenced by RecordSample.
void InitBMHead()
References PARAM::bheight2, bmf, bmh, bmi, bmi2, bmi3, bmi4, bmp, bmpdib, bmPixels, BITMAP_HEADER::boffset, BWCOLS, PARAM::bwidth, BITMAP_HEADER::colours, BITMAP_HEADER::compr, encoderClsid, ERR_CRITICAL, BITMAP_HEADER::filesize, BITMAP_HEADER::headersize, BITMAP_HEADER::height, BITMAP_HEADER::hres, BITMAP_HEADER::imagesize, BITMAP_HEADER::impcol, m_gdiplusToken, OutFileBase, P, BITMAP_HEADER::palette, BITMAP_HEADER::PlanesAndBitspp, BITMAP_HEADER::spare, BITMAP_HEADER::vres, BITMAP_HEADER::width.
Referenced by SetupModel.