CalcInfSusc.cpp
double CalcHouseInf(int j, unsigned short int ts)
References CalcPersonInf, PARAM::CaseIsolationHouseEffectiveness, PERSON::hh, HOST_ISOLATED, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HouseholdDenomLookup, Households, PARAM::HQuarantineHouseEffect, HOUSEHOLD::nhr, P.
Referenced by InfectSweep.
double CalcPlaceInf(int j, int k, unsigned short int ts)
References CalcPersonInf, PARAM::CaseIsolationEffectiveness, HOST_ISOLATED, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HQuarantinePlaceEffect, PERSON::inf, InfStat_Case, P, PARAM::PlaceTypeGroupSizeParam1, PARAM::PlaceTypeTrans, PARAM::SymptPlaceTypeContactRate.
Referenced by InfectSweep.
double CalcSpatialInf(int j, unsigned short int ts)
References CalcPersonInf, PARAM::CaseIsolationEffectiveness, HOST_AGE_GROUP, HOST_ISOLATED, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HQuarantineSpatialEffect, PERSON::inf, InfStat_Case, P, PARAM::RelativeSpatialContact, PARAM::SymptSpatialContactRate.
Referenced by InfectSweep.
double CalcPersonInf(int j, unsigned short int ts)
References HOST_TREATED, HOST_VACCED, Hosts, PARAM::infectiousness, PERSON::latent_time, P, PARAM::TreatInfDrop, PARAM::VaccInfDrop.
Referenced by CalcHouseInf, CalcPlaceInf, CalcSpatialInf.
double CalcHouseSusc(int ai, unsigned short int ts, int infector, int tn)
References CalcPersonSusc, PARAM::CaseIsolationHouseEffectiveness, PARAM::ESocDistHouseholdEffectC, HOST_ISOLATED_DCT, Hosts, PERSON::mcell, Mcells, P, MICROCELL::socdist, PARAM::SocDistHouseholdEffectC.
Referenced by InfectSweep.
double CalcPlaceSusc(int ai, int k, unsigned short int ts, int infector, int tn)
References CalcPersonSusc, PARAM::CaseIsolationEffectiveness, PARAM::ESocDistPlaceEffectC, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HQuarantinePlaceEffect, PERSON::mcell, Mcells, P, MICROCELL::socdist, PARAM::SocDistPlaceEffectC.
Referenced by InfectSweep.
double CalcSpatialSusc(int ai, unsigned short int ts, int infector, int tn)
References CalcPersonSusc, PARAM::CaseIsolationEffectiveness, PARAM::ESocDistSpatialEffectC, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HQuarantineSpatialEffect, PERSON::mcell, Mcells, P, MICROCELL::socdist, PARAM::SocDistSpatialEffectC.
Referenced by InfectSweep.
double CalcPersonSusc(int ai, unsigned short int ts, int infector, int tn)
References PARAM::AgeSusceptibility, HOST_AGE_GROUP, HOST_TREATED, HOST_VACCED, HOST_VACCED_SWITCH, Hosts, P, PERSON::susc, PARAM::TreatSuscDrop, PARAM::VaccSuscDrop, PARAM::VaccSuscDrop2, PARAM::WAIFW_Matrix.
Referenced by CalcHouseSusc, CalcPlaceSusc, CalcSpatialSusc, SeedInfection.