CalcInfSusc.h
SPATIALSIM_CALCINFSUSC_H_
double CalcHouseInf(int, unsigned short int)
References CalcPersonInf, PARAM::CaseIsolationHouseEffectiveness, PERSON::hh, HOST_ISOLATED, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HouseholdDenomLookup, Households, PARAM::HQuarantineHouseEffect, HOUSEHOLD::nhr, P.
Referenced by InfectSweep.
double CalcPlaceInf(int, int, unsigned short int)
References CalcPersonInf, PARAM::CaseIsolationEffectiveness, HOST_ISOLATED, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HQuarantinePlaceEffect, PERSON::inf, InfStat_Case, P, PARAM::PlaceTypeGroupSizeParam1, PARAM::PlaceTypeTrans, PARAM::SymptPlaceTypeContactRate.
Referenced by InfectSweep.
double CalcSpatialInf(int, unsigned short int)
References CalcPersonInf, PARAM::CaseIsolationEffectiveness, HOST_AGE_GROUP, HOST_ISOLATED, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HQuarantineSpatialEffect, PERSON::inf, InfStat_Case, P, PARAM::RelativeSpatialContact, PARAM::SymptSpatialContactRate.
Referenced by InfectSweep.
double CalcPersonInf(int, unsigned short int)
References HOST_TREATED, HOST_VACCED, Hosts, PARAM::infectiousness, PERSON::latent_time, P, PARAM::TreatInfDrop, PARAM::VaccInfDrop.
Referenced by CalcHouseInf, CalcPlaceInf, CalcSpatialInf.
double CalcHouseSusc(int, unsigned short int, int, int)
References CalcPersonSusc, PARAM::CaseIsolationHouseEffectiveness, PARAM::ESocDistHouseholdEffectC, HOST_ISOLATED_DCT, Hosts, PERSON::mcell, Mcells, P, MICROCELL::socdist, PARAM::SocDistHouseholdEffectC.
Referenced by InfectSweep.
double CalcPlaceSusc(int, int, unsigned short int, int, int)
References CalcPersonSusc, PARAM::CaseIsolationEffectiveness, PARAM::ESocDistPlaceEffectC, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HQuarantinePlaceEffect, PERSON::mcell, Mcells, P, MICROCELL::socdist, PARAM::SocDistPlaceEffectC.
Referenced by InfectSweep.
double CalcSpatialSusc(int, unsigned short int, int, int)
References CalcPersonSusc, PARAM::CaseIsolationEffectiveness, PARAM::ESocDistSpatialEffectC, HOST_ISOLATED_DCT, HOST_QUARANTINED, Hosts, PARAM::HQuarantineSpatialEffect, PERSON::mcell, Mcells, P, MICROCELL::socdist, PARAM::SocDistSpatialEffectC.
Referenced by InfectSweep.
double CalcPersonSusc(int, unsigned short int, int, int)
References PARAM::AgeSusceptibility, HOST_AGE_GROUP, HOST_TREATED, HOST_VACCED, HOST_VACCED_SWITCH, Hosts, P, PERSON::susc, PARAM::TreatSuscDrop, PARAM::VaccSuscDrop, PARAM::VaccSuscDrop2, PARAM::WAIFW_Matrix.
Referenced by CalcHouseSusc, CalcPlaceSusc, CalcSpatialSusc, SeedInfection.