Kernels.cpp
double(* Kernel)(double))(double)
Referenced by InitKernel.
double* nKernel
Referenced by InitKernel, numKernel, SetupModel.
double * nKernelHR
Referenced by InitKernel, numKernel, SetupModel.
void InitKernel(int DoPlaces, double norm)
References CellLookup, Cells, dist2_cc_min, ExpKernel, GaussianKernel, Kernel, PARAM::KernelDelta, PARAM::KernelType, PARAM::NCP, NK_HR, nKernel, nKernelHR, NKR, numKernel, P, PowerExpKernel, PowerKernel, PowerKernelB, PowerKernelUS, StepKernel, CELL::tot_prob.
Referenced by AssignPeopleToPlaces, SetupAirports, SetupModel.
double ExpKernel(double r2)
References PARAM::KernelScale, P.
Referenced by InitKernel.
double PowerKernel(double r2)
References PARAM::KernelScale, PARAM::KernelShape, P.
Referenced by InitKernel.
double PowerKernelB(double r2)
References PARAM::KernelScale, PARAM::KernelShape, P.
Referenced by InitKernel.
double PowerKernelUS(double r2)
References PARAM::KernelP3, PARAM::KernelP4, PARAM::KernelScale, PARAM::KernelShape, P.
Referenced by InitKernel.
double GaussianKernel(double r2)
References PARAM::KernelScale, P.
Referenced by InitKernel.
double StepKernel(double r2)
References PARAM::KernelScale, P.
Referenced by InitKernel.
double PowerExpKernel(double r2)
References PARAM::KernelP3, PARAM::KernelP4, PARAM::KernelScale, PARAM::KernelShape, P.
Referenced by InitKernel.
double numKernel(double r2)
References ERR_CRITICAL, PARAM::KernelDelta, NK_HR, nKernel, nKernelHR, NKR, P.
Referenced by AssignPeopleToPlaces, InfectSweep, InitKernel, SetupAirports, TravelDepartSweep.