SharedFuncs.h
SPATIALSIM_SHAREDFUNCS_H_INCLUDED_
void UpdateProbs(int)
References CELL::cum_trans, PARAM::DoDeath, PARAM::DoSIS, CELL::I, CELL::InvCDF, CELL::L, CELL::max_trans, CELL::n, PARAM::NCP, CELL::S, CELL::S0, CELL::tot_prob.
Referenced by AssignPeopleToPlaces, InitModel, RunModel, SetupModel.