Sweep.cpp
void TravelReturnSweep(double t)
References Hosts, HOTEL_PLACE_TYPE, MAX_TRAVEL_TIME, PLACE::members, PLACE::n, PARAM::Nplace, PARAM::NumThreads, P, PERSON::PlaceLinks, Places, PARAM::TimeStep, PERSON::Travelling.
Referenced by RunModel.
void TravelDepartSweep(double t)
References PARAM::AirportCloseEffectiveness, PARAM::AirportCloseTimeStart, PARAM::AirportCloseTimeStartBase, Airports, CellLookup, Cells, PARAM::cheight, AIRPORT::conn_airports, PARAM::cwidth, AIRPORT::DestMcells, AIRPORT::DestPlaces, dist2_raw, PARAM::DoBlanketMoveRestr, HOST_AGE_GROUP, Hosts, HOTEL_PLACE_TYPE, PARAM::HotelPropLocal, Households, INDEXLIST::id, ignpoi_mt, InfStat_Case, InfStat_InfectiousAsymptomaticNotCase, AIRPORT::Inv_DestMcells, AIRPORT::Inv_DestPlaces, AIRPORT::Inv_prop_traffic, CELL::InvCDF, PARAM::InvJourneyDurationDistrib, PARAM::InvLocalJourneyDurationDistrib, CELL::L, PLACE::loc_y, CELL::max_trans, MAX_TRAVEL_TIME, Mcells, PARAM::MeanLocalJourneyTime, MICROCELL::members, PLACE::members, PARAM::MoveRestrDuration, PARAM::MoveRestrEffect, PARAM::MoveRestrRadius2, PARAM::MoveRestrTimeStart, PLACE::n, PARAM::Nairports, PARAM::nch, PARAM::Nplace, AIRPORT::num_mcell, numKernel, PARAM::NumThreads, P, PERSON::PlaceLinks, Places, PARAM::PlaceTypeMeanSize, ranf_mt, PARAM::RelativeTravelRate, CELL::S, CELL::S0, CELL::susceptible, PARAM::TimeStep, AIRPORT::total_traffic, PERSON::Travelling.
Referenced by RunModel.
void InfectSweep(double t, int run)
References MICROCELL::adunit, AdUnits, CalcHouseInf, CalcHouseSusc, CalcPlaceInf, CalcPlaceSusc, CalcSpatialInf, CalcSpatialSusc, POPVAR::cell_inf, CellLookup, Cells, PERSON::contacts, CELL::cum_trans, DAYS_PER_YEAR, PERSON::detected, PARAM::DigitalContactTracingPolicyDuration, ADMINUNIT::DigitalContactTracingTimeStart, PERSON::digitalContactTracingUser, dist2, dist2_raw, PARAM::DoBlanketMoveRestr, PARAM::DoDigitalContactTracing, DoFalseCase, PARAM::DoHouseholds, DoInfect, PARAM::DoPlaces, PARAM::DoSeasonality, ERR_CRITICAL, ERR_CRITICAL_FMT, PARAM::FalsePositiveRate, HOUSEHOLD::FirstPerson, PLACE::group_size, PLACE::group_start, PERSON::hh, HOST_ABSENT, Hosts, HOTEL_PLACE_TYPE, Households, PARAM::HouseholdTrans, CELL::I, ignbin_mt, ignpoi_mt, POPVAR::inf_queue, PERSON::infect_type, INFECT_TYPE_MASK, CELL::infected, PERSON::infector, PARAM::InfQueuePeakLength, InfStat_Dead, InfStat_Susceptible, CELL::InvCDF, HOUSEHOLD::loc_x, PLACE::loc_x, HOUSEHOLD::loc_y, PLACE::loc_y, PARAM::LocalBeta, MAX_CONTACTS, CELL::max_trans, PERSON::mcell, PLACE::mcell, Mcells, PLACE::members, MICROCELL::moverest, PARAM::MoveRestrDuration, PARAM::MoveRestrEffect, PARAM::MoveRestrRadius2, PARAM::MoveRestrTimeStart, PLACE::n, POPVAR::n_queue, PERSON::ncontacts, PARAM::NCP, HOUSEHOLD::nh, NUM_PLACE_TYPES, numKernel, PARAM::NumThreads, P, PERSON::pcell, PLACE_CLOSED, PARAM::PlaceCloseHouseholdRelContact, PARAM::PlaceCloseSpatialRelContact, PERSON::PlaceGroupLinks, PERSON::PlaceLinks, Places, PARAM::PlaceTypeGroupSizeParam1, PARAM::PlaceTypeNum, PARAM::PlaceTypePropBetweenGroupLinks, ranf_mt, CELL::S0, SampleWithoutReplacement, SamplingQueue, PARAM::ScalingFactorPlaceDigitalContacts, PARAM::ScalingFactorSpatialDigitalContacts, PARAM::Seasonality, StateT, CELL::susceptible, PARAM::TimeStep, PARAM::TimeStepsPerDay, CELL::tot_prob, PERSON::Travelling.
Referenced by RunModel.
void IncubRecoverySweep(double t, int run)
References PERSON::absent_start_time, PERSON::absent_stop_time, CellLookup, PLACE::close_end_time, PLACE::close_start_time, PERSON::Critical_time, DoCase, DoCritical, DoDeath, DoDeath_FromCriticalorSARI, DoIncub, DoRecover, DoRecover_FromSeverity, DoRecoveringFromCritical, DoSARI, PARAM::DoSeverity, PARAM::DoSymptoms, PARAM::HolidayDuration, PARAM::HolidayEffect, PARAM::HolidayStartTime, HOST_TREATED, Hosts, CELL::I, CELL::infected, CELL::L, CELL::latent, PERSON::latent_time, PARAM::LatentToSymptDelay, PARAM::N, PARAM::NCP, PARAM::NumHolidays, PARAM::NumThreads, P, PERSON::PlaceLinks, Places, PARAM::PlaceTypeNum, PARAM::PreControlClusterIdHolOffset, ranf_mt, PERSON::RecoveringFromCritical_time, PERSON::recovery_time, PERSON::SARI_time, PARAM::TimeStep, PARAM::TimeStepsPerDay, PERSON::to_die, PARAM::TreatDeathDrop.
Referenced by RunModel.
void DigitalContactTracingSweep(double t)
References AdUnits, POPVAR::cumDCT, POPVAR::cumDCT_adunit, ADMINUNIT::dct, PERSON::dct_end_time, POPVAR::dct_queue, ADMINUNIT::dct_queue, PERSON::dct_start_time, PERSON::digitalContactTraced, PARAM::DigitalContactTracingDelay, PARAM::DigitalContactTracingPolicyDuration, ADMINUNIT::DigitalContactTracingTimeStart, Hosts, PARAM::LengthDigitalContactIsolation, ADMINUNIT::ndct, POPVAR::ndct_queue, ADMINUNIT::ndct_queue, PARAM::NumAdunits, PARAM::NumThreads, P, StateT, PARAM::TimeStepsPerDay.
Referenced by RunModel.
int TreatSweep(double t)
References MICROCELL::adunit, AdUnits, POPVAR::cumT, POPVAR::cumTP, POPVAR::cumUT, dist2_mm, PARAM::DoAdminTriggers, PARAM::DoAdUnits, PARAM::DoGlobalTriggers, PARAM::DoInterventionDelaysByAdUnit, PARAM::DoKeyWorkerProphOnceOnly, PARAM::DoMassVacc, PARAM::DoMoveRestrOnceOnly, PARAM::DoPerCapitaTriggers, DoPlaceClose, PARAM::DoPlaceCloseOnceOnly, PARAM::DoPlaceGroupTreat, DoPlaceOpen, PARAM::DoPlaces, DoProph, DoProphNoDelay, PARAM::DoSocDistOnceOnly, DoVacc, DoVaccNoDelay, PARAM::GlobalIncThreshPop, PLACE::group_start, HOST_TO_BE_TREATED, Hosts, HOTEL_PLACE_TYPE, ADMINUNIT::id, PARAM::IncThreshPop, MICROCELL::keyworkerproph, MICROCELL::keyworkerproph_end_time, MICROCELL::keyworkerproph_trig, PARAM::KeyWorkerProphCellIncThresh, PARAM::KeyWorkerProphDuration, PARAM::KeyWorkerProphRadius2, PARAM::KeyWorkerProphRenewalDuration, PARAM::KeyWorkerProphTimeStart, McellLookup, Mcells, PARAM::mcwidth, MICROCELL::members, MICROCELL::move_end_time, MICROCELL::move_start_time, MICROCELL::move_trig, PARAM::MoveDelayMean, MICROCELL::moverest, PARAM::MoveRestrAdminUnitDivisor, PARAM::MoveRestrByAdminUnit, PARAM::MoveRestrCellIncThresh, PARAM::MoveRestrDuration, PARAM::MoveRestrRadius, PARAM::MoveRestrRadius2, PARAM::MoveRestrTimeStart, POPVAR::mvacc_cum, POPVAR::mvacc_queue, PARAM::N, MICROCELL::n, PLACE::n, POPVAR::n_mvacc, PARAM::nmch, PARAM::NMCP, PARAM::nmcw, MICROCELL::np, ADMINUNIT::NP, POPVAR::np_queue, PARAM::NumThreads, P, POPVAR::p_queue, POPVAR::pg_queue, ADMINUNIT::place_close_trig, MICROCELL::place_end_time, PLACE_TREATED, MICROCELL::place_trig, MICROCELL::placeclose, PARAM::PlaceCloseAdminUnitDivisor, PARAM::PlaceCloseAdunitPropThresh, PARAM::PlaceCloseByAdminUnit, PARAM::PlaceCloseCellIncStopThresh, PARAM::PlaceCloseCellIncThresh, PARAM::PlaceCloseDelayMean, PARAM::PlaceCloseDuration, ADMINUNIT::PlaceCloseDuration, PARAM::PlaceCloseRadius, PARAM::PlaceCloseTimeStart, ADMINUNIT::PlaceCloseTimeStart, Places, PARAM::PlaceTypeNum, ranf_mt, MICROCELL::socdist, MICROCELL::socdist_end_time, MICROCELL::socdist_trig, PARAM::SocDistCellIncStopThresh, PARAM::SocDistCellIncThresh, PARAM::SocDistDuration, PARAM::SocDistTimeStart, ADMINUNIT::SocialDistanceDuration, ADMINUNIT::SocialDistanceTimeStart, State, StateT, PARAM::TimeStepsPerDay, MICROCELL::treat, PLACE::treat, MICROCELL::treat_end_time, PLACE::treat_end_time, MICROCELL::treat_start_time, MICROCELL::treat_trig, PARAM::TreatAdminUnitDivisor, PARAM::TreatByAdminUnit, PARAM::TreatCellIncThresh, PARAM::TreatDelayMean, PARAM::TreatMaxCourses, PARAM::TreatMaxCoursesPerCase, PARAM::TreatPlaceGeogDuration, PARAM::TreatPlaceTotalProp, PARAM::TreatProphCourseLength, PARAM::TreatPropRadial, PARAM::TreatRadius, PARAM::TreatRadius2, PARAM::TreatTimeStart, POPVAR::trigDC, POPVAR::trigDC_adunit, MICROCELL::vacc, MICROCELL::vacc_start_time, MICROCELL::vacc_trig, PARAM::VaccAdminUnitDivisor, PARAM::VaccByAdminUnit, PARAM::VaccCellIncThresh, PARAM::VaccDelayMean, PARAM::VaccMaxCourses, PARAM::VaccMinRadius2, PARAM::VaccProp, PARAM::VaccRadius2, PARAM::VaccTimeStart, PARAM::VaccTimeStartGeo.
Referenced by RunModel.