Update.cpp
void RecordEvent(double, int, int, int, int)
References MICROCELL::adunit, PERSON::hh, Hosts, Households, EVENTS::infectee_adunit, EVENTS::infectee_cell, EVENTS::infectee_ind, EVENTS::infectee_x, EVENTS::infectee_y, PERSON::infector, EVENTS::infector_cell, EVENTS::infector_ind, InfEventLog, PERSON::listpos, EVENTS::listpos, HOUSEHOLD::loc_x, HOUSEHOLD::loc_y, PERSON::mcell, Mcells, nEvents, P, PERSON::pcell, EVENTS::run, PARAM::SpatialBoundingBox, EVENTS::t, EVENTS::t_infector, EVENTS::thread, PARAM::TimeStepsPerDay, EVENTS::type.
Referenced by DoInfect.
unsigned short int ChooseFromICDF(double *, double, int)
References CDF_RES, P, ranf_mt, PARAM::TimeStepsPerDay.
Referenced by DoIncub.
int ChooseFinalDiseaseSeverity(int, int)
References P, PARAM::Prop_Critical_ByAge, PARAM::Prop_ILI_ByAge, PARAM::Prop_SARI_ByAge, ranf_mt, Severity_Critical, Severity_ILI, Severity_Mild, Severity_SARI.
Referenced by DoIncub.
void DoImmune(int ai)
References PARAM::bheight, bmh, bmi3, PARAM::bminx, PARAM::bminy, PARAM::bwidth, Cells, PERSON::hh, Hosts, Households, CELL::I, PERSON::inf, CELL::infected, InfStat_ImmuneAtStart, InfStat_Susceptible, CELL::L, CELL::latent, PERSON::listpos, HOUSEHOLD::loc_x, HOUSEHOLD::loc_y, PARAM::OutputBitmap, P, PERSON::pcell, CELL::R, CELL::S, PARAM::scalex, PARAM::scaley, CELL::susceptible, BITMAP_HEADER::width.
Referenced by InitModel.
void DoInfect(int ai, double t, int tn, int run)
References MICROCELL::adunit, PARAM::bheight, bmh, bmi2, PARAM::bminx, PARAM::bminy, PARAM::bwidth, CDF_RES, Cells, POPVAR::cumI, POPVAR::cumI_adunit, POPVAR::cumI_keyworker, POPVAR::cumIa, POPVAR::cumItype, PARAM::DoAdUnits, DoCase, DoIncub, PARAM::DoLatent, PARAM::DoOneGen, PARAM::DoRecordInfEvents, DoRecover, PERSON::hh, HOST_AGE_GROUP, Hosts, Households, PERSON::inf, PERSON::infect_type, INFECT_TYPE_MASK, PERSON::infection_time, InfStat_Latent, InfStat_Susceptible, PERSON::keyworker, CELL::L, CELL::latent, PARAM::latent_icdf, PERSON::latent_time, PARAM::LatentPeriod, PERSON::listpos, HOUSEHOLD::loc_x, HOUSEHOLD::loc_y, PARAM::LocationInitialInfection, PARAM::MaxInfEvents, POPVAR::maxRad2, PERSON::mcell, Mcells, nEvents, PARAM::OutputBitmap, PARAM::OutputBitmapDetected, P, PERSON::pcell, ranf_mt, RecordEvent, CELL::S, PARAM::scalex, PARAM::scaley, StateT, POPVAR::sumRad2, CELL::susceptible, PARAM::TimeStepsPerDay, BITMAP_HEADER::width.
Referenced by InfectSweep, SeedInfection.
void DoMild(int ai, int tn)
References MICROCELL::adunit, POPVAR::cumMild, POPVAR::cumMild_adunit, PARAM::DoAdUnits, PARAM::DoSeverity, Hosts, PERSON::mcell, Mcells, POPVAR::Mild, POPVAR::Mild_adunit, P, Severity_Asymptomatic, PERSON::Severity_Current, Severity_Mild, StateT.
Referenced by DoCase.
void DoILI(int ai, int tn)
References MICROCELL::adunit, POPVAR::cumILI, POPVAR::cumILI_adunit, PARAM::DoAdUnits, PARAM::DoSeverity, Hosts, POPVAR::ILI, POPVAR::ILI_adunit, PERSON::mcell, Mcells, P, Severity_Asymptomatic, PERSON::Severity_Current, Severity_ILI, StateT.
Referenced by DoCase.
void DoSARI(int ai, int tn)
References MICROCELL::adunit, POPVAR::cumSARI, POPVAR::cumSARI_adunit, PARAM::DoAdUnits, PARAM::DoSeverity, Hosts, POPVAR::ILI, POPVAR::ILI_adunit, PERSON::mcell, Mcells, P, POPVAR::SARI, POPVAR::SARI_adunit, PERSON::Severity_Current, Severity_ILI, Severity_SARI, StateT.
Referenced by IncubRecoverySweep.
void DoCritical(int ai, int tn)
References MICROCELL::adunit, POPVAR::Critical, POPVAR::Critical_adunit, POPVAR::cumCritical, POPVAR::cumCritical_adunit, PARAM::DoAdUnits, PARAM::DoSeverity, Hosts, PERSON::mcell, Mcells, P, POPVAR::SARI, POPVAR::SARI_adunit, Severity_Critical, PERSON::Severity_Current, Severity_SARI, StateT.
Referenced by IncubRecoverySweep.
void DoRecoveringFromCritical(int ai, int tn)
References MICROCELL::adunit, POPVAR::Critical, POPVAR::Critical_adunit, POPVAR::CritRecov, POPVAR::CritRecov_adunit, POPVAR::cumCritRecov, POPVAR::cumCritRecov_adunit, PARAM::DoAdUnits, PARAM::DoSeverity, Hosts, PERSON::mcell, Mcells, P, Severity_Critical, PERSON::Severity_Current, Severity_RecoveringFromCritical, StateT, PERSON::to_die.
Referenced by IncubRecoverySweep.
void DoDeath_FromCriticalorSARI(int ai, int tn)
References MICROCELL::adunit, POPVAR::Critical, POPVAR::Critical_adunit, PARAM::DoAdUnits, PARAM::DoSeverity, Hosts, PERSON::mcell, Mcells, P, POPVAR::SARI, POPVAR::SARI_adunit, Severity_Critical, PERSON::Severity_Current, Severity_Dead, Severity_SARI, StateT.
Referenced by IncubRecoverySweep.
void DoRecover_FromSeverity(int ai, int tn)
References MICROCELL::adunit, POPVAR::CritRecov, POPVAR::CritRecov_adunit, PARAM::DoAdUnits, PARAM::DoSeverity, Hosts, POPVAR::ILI, POPVAR::ILI_adunit, PERSON::inf, InfStat_Case, InfStat_InfectiousAsymptomaticNotCase, PERSON::mcell, Mcells, POPVAR::Mild, POPVAR::Mild_adunit, P, POPVAR::SARI, POPVAR::SARI_adunit, PERSON::Severity_Current, Severity_ILI, Severity_Mild, Severity_Recovered, Severity_RecoveringFromCritical, Severity_SARI, StateT.
Referenced by IncubRecoverySweep.
void DoIncub(int ai, unsigned short int ts, int tn, int run)
References PARAM::AgeInfectiousness, Cells, PARAM::CFR_Critical_ByAge, PARAM::CFR_SARI_ByAge, ChooseFinalDiseaseSeverity, ChooseFromICDF, PARAM::ControlPropCasesId, PERSON::Critical_time, PARAM::CriticalToCritRecov_icdf, PARAM::CriticalToDeath_icdf, PARAM::CritRecovToRecov_icdf, PERSON::detected, PARAM::DoInfectiousnessProfile, PARAM::DoSeverity, gen_gamma_mt, HOST_AGE_GROUP, HOST_TREATED, HOST_VACCED, Hosts, CELL::I, PARAM::ILIToRecovery_icdf, PARAM::ILIToSARI_icdf, PERSON::inf, CELL::infected, PARAM::infectious_icdf, PERSON::infectiousness, PARAM::InfectiousnessGamA, PARAM::InfectiousnessGamR, PARAM::InfectiousnessSD, PARAM::InfectiousPeriod, InfStat_InfectiousAlmostSymptomatic, InfStat_InfectiousAsymptomaticNotCase, InfStat_Latent, CELL::L, CELL::latent, PERSON::latent_time, PERSON::listpos, PARAM::Mean_CriticalToCritRecov, PARAM::Mean_CriticalToDeath, PARAM::Mean_CritRecovToRecov, PARAM::Mean_ILIToRecovery, PARAM::Mean_ILIToSARI, PARAM::Mean_MildToRecovery, PARAM::Mean_SARIToCritical, PARAM::Mean_SARIToRecovery, PARAM::MildToRecovery_icdf, NUM_AGE_GROUPS, P, PERSON::pcell, PARAM::ProportionSymptomatic, ranf_mt, PERSON::RecoveringFromCritical_time, PERSON::recovery_time, CELL::S, PERSON::SARI_time, PARAM::SARIToCritical_icdf, PARAM::SARIToRecovery_icdf, Severity_Critical, PERSON::Severity_Final, Severity_Mild, Severity_SARI, CELL::susceptible, PARAM::SymptInfectiousness, PARAM::TimeStepsPerDay, PERSON::to_die, PARAM::TreatSympDrop, PARAM::VaccSympDrop.
Referenced by DoInfect, IncubRecoverySweep.
void DoDetectedCase(int ai, double t, unsigned short int ts, int tn)
References PERSON::absent_start_time, PERSON::absent_stop_time, MICROCELL::adunit, AdUnits, PARAM::CaseAbsentChildAgeCutoff, PARAM::CaseAbsentChildPropAdultCarers, ADMINUNIT::CaseIsolationDuration, PARAM::CaseIsolationPolicyDuration, PARAM::CaseIsolationProp, ADMINUNIT::CaseIsolationTimeStart, PERSON::contacts, POPVAR::cumAA, POPVAR::cumAC, POPVAR::cumACS, POPVAR::cumAH, POPVAR::cumHQ, POPVAR::cumV, POPVAR::dct_queue, PARAM::DigitalContactTracingPolicyDuration, ADMINUNIT::DigitalContactTracingTimeStart, PARAM::DoAdminTriggers, PARAM::DoDigitalContactTracing, PARAM::DoGlobalTriggers, PARAM::DoHouseholds, PARAM::DoHQretrigger, PARAM::DoInterventionDelaysByAdUnit, PARAM::DoMassVacc, DoPlaceClose, PARAM::DoPlaceGroupTreat, PARAM::DoPlaces, DoProph, PARAM::DoRealSymptWithdrawal, DoTreatCase, DoVacc, HOUSEHOLD::FirstPerson, PERSON::hh, HOST_ABSENT, HOST_AGE_YEAR, HOST_QUARANTINED, HOST_TO_BE_QUARANTINED, HOST_TO_BE_TREATED, Hosts, HOTEL_PLACE_TYPE, Households, ADMINUNIT::HQuarantineDuration, PARAM::HQuarantineHouseDelay, PARAM::HQuarantinePolicyDuration, PARAM::HQuarantinePropHouseCompliant, PARAM::HQuarantinePropIndivCompliant, ADMINUNIT::HQuarantineTimeStart, InfStat_Dead, PERSON::isolation_start_time, MICROCELL::keyworkerproph_trig, PERSON::mcell, PLACE::mcell, Mcells, MICROCELL::move_trig, PERSON::ncontacts, POPVAR::ndct_queue, HOUSEHOLD::nh, POPVAR::np_queue, NUM_PLACE_TYPES_NOAIR, P, POPVAR::p_queue, POPVAR::pg_queue, MICROCELL::place_trig, PARAM::PlaceCloseTimeStart, PERSON::PlaceGroupLinks, PERSON::PlaceLinks, Places, PARAM::PlaceTypeNum, PARAM::ProportionDigitalContactsIsolate, PERSON::quar_comply, PERSON::quar_start_time, ranf_mt, MICROCELL::socdist_trig, State, StateT, PARAM::TimeStepsPerDay, PLACE::treat, MICROCELL::treat_trig, PARAM::TreatHouseholdsDuration, PARAM::TreatPlaceGeogDuration, PARAM::TreatPlaceProbCaseId, PARAM::TreatPropCaseHouseholds, PARAM::TreatPropCases, PARAM::TreatTimeStart, PARAM::usCaseAbsenteeismDelay, PARAM::usCaseIsolationDelay, PARAM::usCaseIsolationDuration, MICROCELL::vacc_trig, PARAM::VaccHouseholdsDuration, PARAM::VaccMaxCourses, PARAM::VaccPropCaseHouseholds, PARAM::VaccTimeStart.
Referenced by DoCase, DoFalseCase.
void DoCase(int ai, double t, unsigned short int ts, int tn)
References PERSON::absent_start_time, PERSON::absent_stop_time, MICROCELL::adunit, PARAM::CaseAbsentChildAgeCutoff, PARAM::CaseAbsentChildPropAdultCarers, Cells, MICROCELL::country, POPVAR::cumAA, POPVAR::cumAC, POPVAR::cumACS, POPVAR::cumC, POPVAR::cumC_adunit, POPVAR::cumC_country, POPVAR::cumC_keyworker, POPVAR::cumCa, POPVAR::cumDC, POPVAR::cumDC_adunit, CELL::cumTC, PARAM::DoAdminTriggers, PARAM::DoAdUnits, DoDetectedCase, PARAM::DoGlobalTriggers, PARAM::DoHouseholds, DoILI, DoMild, DoPlaceClose, PARAM::DoPlaces, PARAM::DoSeverity, HOUSEHOLD::FirstPerson, PERSON::hh, HOST_ABSENT, HOST_AGE_GROUP, HOST_AGE_YEAR, HOST_QUARANTINED, HOST_TREATED, Hosts, HOTEL_PLACE_TYPE, Households, PERSON::inf, InfStat_Case, InfStat_Dead, InfStat_InfectiousAlmostSymptomatic, PERSON::keyworker, PERSON::mcell, Mcells, HOUSEHOLD::nh, NUM_AGE_GROUPS, NUM_PLACE_TYPES_NOAIR, P, PERSON::pcell, PARAM::PlaceCloseTimeStart, PERSON::PlaceLinks, PARAM::PlaceTypeNum, ranf_mt, PERSON::Severity_Final, Severity_Mild, StateT, PARAM::SymptPlaceTypeWithdrawalProp, PARAM::usCaseAbsenteeismDelay, PARAM::usCaseAbsenteeismDuration, PARAM::usCaseIsolationDelay, PARAM::usCaseIsolationDuration.
Referenced by DoInfect, IncubRecoverySweep.
void DoFalseCase(int ai, double t, unsigned short int ts, int tn)
References PARAM::ControlPropCasesId, POPVAR::cumDC, POPVAR::cumFC, DoDetectedCase, PARAM::DoEarlyCaseDiagnosis, Hosts, P, PARAM::PreControlClusterIdCaseThreshold, ranf_mt, State, StateT.
Referenced by InfectSweep, RunModel.
void DoRecover(int ai, int run, int tn)
References PARAM::bheight, bmh, bmi2, bmi3, PARAM::bminx, PARAM::bminy, PARAM::bwidth, Cells, PERSON::detected, PARAM::DoSIS, PERSON::hh, Hosts, Households, CELL::I, PERSON::inf, CELL::infected, PERSON::infector, InfStat_Case, InfStat_InfectiousAsymptomaticNotCase, InfStat_Recovered, InfStat_Susceptible, CELL::L, CELL::latent, PERSON::listpos, HOUSEHOLD::loc_x, HOUSEHOLD::loc_y, PARAM::OutputBitmap, PARAM::OutputBitmapDetected, P, PERSON::pcell, CELL::R, CELL::S, PARAM::scalex, PARAM::scaley, PERSON::susc, CELL::susceptible, PARAM::SuscReductionFactorPerInfection, BITMAP_HEADER::width.
Referenced by DoInfect, IncubRecoverySweep.
void DoDeath(int ai, int tn, int run)
References MICROCELL::adunit, PARAM::bheight, bmh, bmi2, bmi3, PARAM::bminx, PARAM::bminy, PARAM::bwidth, Cells, POPVAR::cumD_adunit, POPVAR::cumDa, CELL::D, PERSON::detected, PARAM::DoAdUnits, PERSON::hh, HOST_AGE_GROUP, Hosts, Households, CELL::I, PERSON::inf, CELL::infected, InfStat_Case, InfStat_Dead, InfStat_InfectiousAsymptomaticNotCase, CELL::L, PERSON::listpos, HOUSEHOLD::loc_x, HOUSEHOLD::loc_y, PERSON::mcell, Mcells, PARAM::OutputBitmap, PARAM::OutputBitmapDetected, P, PERSON::pcell, CELL::S, PARAM::scalex, PARAM::scaley, StateT, CELL::susceptible, BITMAP_HEADER::width.
Referenced by IncubRecoverySweep.
void DoTreatCase(int ai, unsigned short int ts, int tn)
References MICROCELL::adunit, PARAM::bheight, bmh, bmi4, PARAM::bminx, PARAM::bminy, PARAM::bwidth, Cells, POPVAR::cumT, POPVAR::cumT_adunit, POPVAR::cumT_keyworker, CELL::cumTC, POPVAR::cumUT, PARAM::DoAdUnits, HOST_TO_BE_TREATED, Hosts, Households, InfStat_Dead_WasAsymp, InfStat_Susceptible, PERSON::keyworker, HOUSEHOLD::loc_y, PERSON::mcell, Mcells, PARAM::OutputBitmap, P, PERSON::pcell, PARAM::scalex, PARAM::scaley, State, StateT, PARAM::TimeStepsPerDay, CELL::tot_treat, PERSON::treat_start_time, PERSON::treat_stop_time, PARAM::TreatCaseCourseLength, PARAM::TreatDelayMean, PARAM::TreatMaxCourses, BITMAP_HEADER::width.
Referenced by DoDetectedCase.
void DoProph(int ai, unsigned short int ts, int tn)
References MICROCELL::adunit, PARAM::bheight, bmh, bmi4, PARAM::bminx, PARAM::bminy, PARAM::bwidth, Cells, POPVAR::cumT, POPVAR::cumT_adunit, POPVAR::cumT_keyworker, POPVAR::cumUT, PARAM::DoAdUnits, Hosts, Households, PERSON::keyworker, HOUSEHOLD::loc_y, PERSON::mcell, Mcells, PARAM::OutputBitmap, P, PARAM::scalex, PARAM::scaley, State, StateT, PARAM::TimeStepsPerDay, CELL::tot_treat, PERSON::treat_start_time, PERSON::treat_stop_time, PARAM::TreatDelayMean, PARAM::TreatMaxCourses, PARAM::TreatProphCourseLength, BITMAP_HEADER::width.
Referenced by DoDetectedCase, TreatSweep.
void DoProphNoDelay(int ai, unsigned short int ts, int tn, int nc)
References MICROCELL::adunit, PARAM::bheight, bmh, bmi4, PARAM::bminx, PARAM::bminy, PARAM::bwidth, Cells, POPVAR::cumT, POPVAR::cumT_adunit, POPVAR::cumT_keyworker, PARAM::DoAdUnits, Hosts, Households, PERSON::keyworker, HOUSEHOLD::loc_y, PERSON::mcell, Mcells, PARAM::OutputBitmap, P, PARAM::scalex, PARAM::scaley, State, StateT, PARAM::TimeStepsPerDay, CELL::tot_treat, PERSON::treat_start_time, PERSON::treat_stop_time, PARAM::TreatMaxCourses, PARAM::TreatProphCourseLength, BITMAP_HEADER::width.
Referenced by TreatSweep.
void DoPlaceClose(int i, int j, unsigned short int ts, int tn, int DoAnyway)
References PERSON::absent_start_time, PERSON::absent_stop_time, MICROCELL::adunit, AdUnits, PARAM::CaseAbsentChildAgeCutoff, PARAM::CaseAbsentChildPropAdultCarers, PLACE::close_end_time, PLACE::close_start_time, PLACE::control_trig, POPVAR::cumAPA, POPVAR::cumAPCS, PARAM::DoInterventionDelaysByAdUnit, PARAM::DoPlaceCloseOnceOnly, PARAM::DoRealSymptWithdrawal, HOUSEHOLD::FirstPerson, PERSON::hh, HOST_ABSENT, HOST_AGE_YEAR, HOST_QUARANTINED, Hosts, Households, InfStat_Dead, PLACE::mcell, Mcells, PLACE::members, PARAM::N, PLACE::n, HOUSEHOLD::nh, NUM_PLACE_TYPES_NOAIR, P, ADMINUNIT::place_close_trig, PARAM::PlaceCloseAdunitPlaceTypes, PARAM::PlaceCloseByAdminUnit, PARAM::PlaceCloseCasePropThresh, PARAM::PlaceCloseDelayMean, PARAM::PlaceCloseDuration, ADMINUNIT::PlaceCloseDuration, PARAM::PlaceCloseEffect, PARAM::PlaceCloseFracIncTrig, PARAM::PlaceCloseIncTrig, Places, ranf_mt, StateT, PARAM::TimeStepsPerDay, PARAM::usCaseAbsenteeismDuration.
Referenced by DoCase, DoDetectedCase, TreatSweep.
void DoPlaceOpen(int i, int j, unsigned short int ts, int tn)
References PERSON::absent_stop_time, PARAM::CaseAbsentChildAgeCutoff, PLACE::close_end_time, POPVAR::cumAPCS, PARAM::DoRealSymptWithdrawal, HOUSEHOLD::FirstPerson, PERSON::hh, HOST_ABSENT, HOST_AGE_YEAR, HOST_QUARANTINED, Hosts, Households, InfStat_Dead, PLACE::members, PLACE::n, HOUSEHOLD::nh, NUM_PLACE_TYPES_NOAIR, P, Places, StateT, PARAM::TimeStepsPerDay.
Referenced by TreatSweep.
int DoVacc(int ai, unsigned short int ts)
References PARAM::bheight, bmh, bmi4, PARAM::bminx, PARAM::bminy, PARAM::bwidth, Cells, POPVAR::cumV, POPVAR::cumV_daily, PARAM::DoDistributionVaccination, PERSON::hh, HOST_TO_BE_VACCED, Hosts, Households, InfStat_Dead_WasAsymp, InfStat_InfectiousAlmostSymptomatic, HOUSEHOLD::loc_y, PARAM::OutputBitmap, P, PERSON::pcell, PARAM::scalex, PARAM::scaley, State, PARAM::TimeStepsPerDay, CELL::tot_vacc, PERSON::vacc_start_time, PARAM::VaccDelayMean, PARAM::VaccDosePerDay, PARAM::VaccMaxCourses, BITMAP_HEADER::width.
Referenced by DoDetectedCase, TreatSweep.
void DoVaccNoDelay(int ai, unsigned short int ts)
References PARAM::bheight, bmh, bmi4, PARAM::bminx, PARAM::bminy, PARAM::bwidth, Cells, POPVAR::cumVG, POPVAR::cumVG_daily, PERSON::hh, HOST_TO_BE_VACCED, Hosts, Households, InfStat_Dead_WasAsymp, InfStat_InfectiousAlmostSymptomatic, HOUSEHOLD::loc_y, PARAM::OutputBitmap, P, PERSON::pcell, PARAM::scalex, PARAM::scaley, State, CELL::tot_vacc, PERSON::vacc_start_time, PARAM::VaccDosePerDay, PARAM::VaccMaxCourses, BITMAP_HEADER::width.
Referenced by TreatSweep.