binio.h
size_t fwrite_big(void *, size_t, size_t, FILE *)
Referenced by OutputBitmap, SavePeopleToPlaces, SaveSnapshot, SetupPopulation, zfwrite_big.
size_t fread_big(void *, size_t, size_t, FILE *)
Referenced by LoadPeopleToPlaces, LoadSnapshot, SetupModel, SetupPopulation, zfread_big.
size_t zfwrite_big(void *, size_t, size_t, FILE *)
References fwrite_big.
Referenced by SaveSnapshot.
size_t zfread_big(void *, size_t, size_t, FILE *)
References fread_big.
Referenced by LoadSnapshot.