binio.cpp
COMP_LEVEL
size_t fwrite_big(void *buffer, size_t size, size_t count, FILE *stream)
Referenced by OutputBitmap, SavePeopleToPlaces, SaveSnapshot, SetupPopulation, zfwrite_big.
size_t fread_big(void *buffer, size_t size, size_t count, FILE *stream)
Referenced by LoadPeopleToPlaces, LoadSnapshot, SetupModel, SetupPopulation, zfread_big.
size_t zfwrite_big(void *buffer, size_t size, size_t count, FILE *stream)
References fwrite_big.
Referenced by SaveSnapshot.
size_t zfread_big(void *buffer, size_t size, size_t count, FILE *stream)
References fread_big.
Referenced by LoadSnapshot.